### ISSUE TITLE
Can't find pokegoapi

### ISSUE THREAD

**Issue by pashorizer** [SwipeX/PokeMate#1]
Okay I am doing something wrong.

`import com.pokegoapi.api.inventory.Bag;`
`context.getApi().getBag()`

I can't find that import, it says the symbol does not exist. I checked the PokemonGo Class and there is not even a method `getBag()`. Do I need to manually pull the newest PokemonGoAPI by myself?

**Comment by pashorizer** [comment]
Changed it to `.getInventories().getItemBag()` and its finding it at least. Is the project actually up to date?

**Comment by SwipeX** [comment]
This is a result of https://github.com/Grover-c13/PokeGOAPI-Java/pull/131/files.
They updated the API without deprecation, which caused the error.

**Comment by SwipeX** [comment]
fixed in ba33a52afb3f420c6cbff2de71e6f30ffc9359c4
