### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by SonnyX** [SwipeX/PokeMate#100]
Application heaps up a huge amount of memory somewhere.
Needs investigation.

**Comment by BurakDev** [comment]
UI enabled ?

**Comment by SonnyX** [comment]
@BurakDev When I noticed it: yes, now running console mode only.
If my system dies again then its not only UI.

**Comment by SippieCup** [comment]
I bet its the iterator that was added in the evolution task. I'll look into it when I get home.

**Comment by SonnyX** [comment]
It's UI related, my memory stays clean in console only mode.

**Comment by BurakDev** [comment]
Same issue for me, 50 minutes runtime, 550 Mbit memory used and grow up indefinitely. (Ubuntu 14.04)

But it grow up slowly and I don't think we can do anything about this. (making external web interface with a webAPI on main project ?)

**Comment by kylestev** [comment]
if someone is able to determine if this is contingent on the non-console
version (i.e. visible map) it would help us resolve this quicker. thank you
for reporting this bug y'all!

**Comment by RobertMcCoy** [comment]
No UI, I get a consistent ~250Mb Java process.

With UI I get a memory leak as well. My findings with modifying UPDATE_TIME are that if you set it to a low time (~1000ms) the memory leak amplifies enormously, but setting it to a really, really high update time (~500000ms) appears to completely stop the leak. There is an uptick in memory usage every now and then but it evens out.

However, whenever a toast message appears, the memory jumps up ~4-10 Mb, and it never comes down. I don't know terribly much about toast messages, but are they supposed to be manually disposed, or do they automatically get garbage collected?

**Comment by kylestev** [comment]
my guess is that the memory leak is still present if update time is large. this does seem like it narrows down the scope of where the leak is present. @SwipeX or myself will take a closer look. thanks again for the detailed report. it makes our lives a lot easier!

**Comment by SwipeX** [comment]
Its the webkit. Apparently the javafx does a poor job of handling javascript objects.

**Comment by SwipeX** [comment]
jxbrowser could be a solution, it is free for open source projects.

**Comment by SwipeX** [comment]
#119
