### ISSUE TITLE
GUI not opening

### ISSUE THREAD

**Issue by rawkus123** [SwipeX/PokeMate#106]
No matter what i do i cant seem to make a GUI open... only the command line bot is happening

ill list the steps ive used so far...
Download source / zip... extract to x:\PokeMate....
Config.properties changed
Download PokeMate.jar from releases tab place in x:\PokeMate
Run from cmdline: java -jar pokemate.jar
starts command line bot.....

Install IDEA and import project....
Run from Application-Run in right hand pane view of grandle
Runs command line bot inside IDEA....

Run gradlew.bat from CMD ... Gradle completes (checked via gradlew from prompt)
use cmd: gradlew fatjar ... build is successful
use cmd: gradlew run
starts cmd line bot
all these attempts are fresh attempts aswell new directory etc...
Forgot to mention the bots run fine in cmd though... just would like a GUI lol

**Comment by Sorries** [comment]
I used Intellij Ultimate version as the community version doesn't work for me. In Intellij  I ran the build.gradle first. Then I  run on PokeMate from main/java/dekk.pw.pokemate/pokemate. 

and of course, it should be set to true within config files.

**Comment by SwipeX** [comment]
Do you have show=true?

**Comment by SippieCup** [comment]
I was about to say, the default config has the gui disabled!

**Comment by rawkus123** [comment]
-.- gg

**Comment by rawkus123** [comment]
Off Topic - how come no matter which email i throw into the config it still logs me into the same account?

**Comment by RobertMcCoy** [comment]
Delete your token.txt and build folders if your are compiling from within Gradle, that appears to fix the issue.

**Comment by SwipeX** [comment]
@rawkus123 you need a seperate config file for each account.
