### ISSUE TITLE
standing in the atlantic ocean

### ISSUE THREAD

**Issue by goteksc** [SwipeX/PokeMate#107]
Hm, I'm standing in the atlantic ocean. What am I doing wrong?
![ss 2016-07-27 at 03 29 50](https://cloud.githubusercontent.com/assets/5453361/17161111/ea08de66-53aa-11e6-97cb-b8c1c665889c.png)

I'ts also doing nothing but walking, but the origin/destination coordinates don't match up with the gui at all.
I'm using the released jar, launching it through cmd and with a ptc account. Is there a logfile that I can share?

**Comment by RobertMcCoy** [comment]
Can you share your config.properties file?

**Comment by goteksc** [comment]
Ofc, here you go
[config.txt](https://github.com/SwipeX/PokeMate/files/385117/config.txt)

**Comment by RobertMcCoy** [comment]
The longitude and latitude you have entered on that file are right where you are shown standing in your image. Go to Google Maps or Pokevision, and copy the Longitude/Latitude that those sites give you and put them in the correct place on the file, and try running it again.

**Comment by goteksc** [comment]
Got a - with the latitude >.< T

Many thanks, would've never seen that myself.

**Comment by RobertMcCoy** [comment]
No problem
