### ISSUE TITLE
Egg display

### ISSUE THREAD

**Issue by SwipeX** [SwipeX/PokeMate#108]
Show the eggs with a progress bar either with the pokemon/ on their own tab.

**Comment by BurakDev** [comment]
API method to get eggs status exist ?

**Comment by mjmjelde** [comment]
Yes it does.  Its in the EggIncubator classes

**Comment by BurakDev** [comment]
Working on display of incubator and eggs  on UI !

**Comment by BurakDev** [comment]
@SwipeX You still want the progressbar ? I can implement it to complete this issue, if don't need just close this :smile:

**Comment by SwipeX** [comment]
progressbar would be nice yeah
