### ISSUE TITLE
Exception in thread-15

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#12]
https://i.imgur.com/2d2gVSP.png

When you get this error the map stops working/updating/moving but it looks like the bot continues

**Comment by SwipeX** [comment]
Got a fix coming up for this, it has to do with how pokestops were set up. Expect it next version.

**Comment by Simpuhl** [comment]
Cool ty, plz do a new release when its done since I have no idea how to compile

**Comment by SwipeX** [comment]
released.
