### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#128]
i got this with the last release

![capture](https://cloud.githubusercontent.com/assets/20646280/17183958/1df702fa-542a-11e6-8d99-42b3a0456654.PNG)

**Comment by BurakDev** [comment]
Can you provide better capture ?

**Comment by EiTeR94** [comment]
![capture](https://cloud.githubusercontent.com/assets/20646280/17184028/71e70482-542a-11e6-83ae-7e32730b6b3b.PNG)

i can't do mush better, the bot run normaly, but i got this error all the time on the console

**Comment by SwipeX** [comment]
oh. yeah that was my fault.
Ill fix that.

**Comment by EiTeR94** [comment]
Ok mate thx for your work :)

**Comment by SwipeX** [comment]
Redownload 0.2.0 for the reflected fix.

**Comment by EiTeR94** [comment]
Perfect, thx you :)
