### ISSUE TITLE
Pokeballs running out quickly.

### ISSUE THREAD

**Issue by paradoxism13** [SwipeX/PokeMate#13]
The automation is running out of pokeballs rather quickly. How do I set it up to use pokeballs, great balls and ultraballs in that order?

**Comment by Simpuhl** [comment]
I had over 200 balls and then captured about 20-30 pokemon and ran out. Not sure if it misses or not but it looks like it does.

It would be nice to do this feature to use other balls or use specific balls for specific CP levels.

Ex use a normal ball for any level or if no other balls

use a better ball if cp level is 500+

use best ball is cp level is 800+

My only way around this so far is to find an area with a shit ton of poke stops so i dont run out of balls

**Comment by paradoxism13** [comment]
If you put preferred_ball="ITEM_GREAT_BALL" in the config, will it still use normal pokeballs when it runs out of its preferred throw item? Will it even pick up normal pokeballs? I can't test it right now.

**Comment by SwipeX** [comment]
@paradoxism13 yes it will use whatever you have if it runs out.

**Comment by SwipeX** [comment]
the short of it is, find a location that has more pokestops.
