### ISSUE TITLE
Bring back option to see exp per hour

### ISSUE THREAD

**Issue by aupperk24** [SwipeX/PokeMate#131]
Just got the 0.2.0 version and I think the notifications are great, but I think it would be awesome to bring back those line by line exp info in the console. Is there a way to manually add that back?

**Comment by BurakDev** [comment]
You can set console_notification to true to output all notifications to console.

**Comment by SwipeX** [comment]
The exp/h has been removed, but it is actually a notable feature.

**Comment by elmagow** [comment]
Also transfer has disappeared

**Comment by SwipeX** [comment]
@elmagow because it becomes a big spam list when a pokemon is caught. Though maybe it could tack on to the existing notification.

**Comment by RobertMcCoy** [comment]
I'm going to add in a minimum CP property that will only display toast messages for pokemon above a user specified CP (default 0), yet will keep every pokemon caught in the log. I will also add back in the XP/Hr and Pokemon Release message into the log within the UI. I think that should be a happy medium for individuals to check without getting the console or UI spammed.

**Comment by SippieCup** [comment]
This has been added and can be closed.
