### ISSUE TITLE
Do Not Transfer Items Config

### ISSUE THREAD

**Issue by ssbtoday** [SwipeX/PokeMate#132]
So... Unfortunately I just ran the newest version of the bot, and I just got to experience the biggest cringe of my life. It transferred all 94 Hyper Potions I had, and as far as I looked into the config, there's no option to specify what items to keep. So now I have 0 Hyper Potions and far too many pokeballs, and I would definitely like an option to NEVER transfer certain items.

**Comment by iDreamInBinary** [comment]
If you are running the bot from an IDE  you can remove the items you dont want to be dropped from the UNWANTED - Array in DropItems.java

But I agree there should be a way to change it in the config file

**Comment by RobertMcCoy** [comment]
This has been added in #135
