### ISSUE TITLE
[Bug] Google-based logins require manual reauthentication

### ISSUE THREAD

**Issue by ghost** [SwipeX/PokeMate#133]
Currently, the jar wants a token in token/c83657d439b303f4ec6e130a07311340.txt, but it doesn't make that folder by itself.

Temporary workaround: create a new folder called tokens, login and reauthenticate (or if you have your old token, rename that to the .txt file above)

**Comment by BurakDev** [comment]
The filename is based on md5sum of username.

And I forgot to auto-create directory because I work with git and I forgot the .jar file user.

I will correct this for next update.

**Comment by SwipeX** [comment]
make a folder called 'tokens' for now to fix.
