### ISSUE TITLE
what does whitelist pokemon mean?

### ISSUE THREAD

**Issue by massivemark** [SwipeX/PokeMate#143]
What does whitelist pokemon mean?

**Comment by RobertMcCoy** [comment]
Whitelist means only evolve the pokemon on the whitelist, so if you put 10 on there, only weedle (I think that's weedle) will evolve.

**Comment by kyleshrader** [comment]
I think the comment was a typo. It should say "Only evolve certain pokemon". Now we have 3 lists in config... transfer blacklist and evolve-pokemon/drop-items whitelists... so maybe the property key should be updated to be more understandable

**Comment by massivemark** [comment]
thank you

**Comment by RobertMcCoy** [comment]
After swipe merges all the pull requests I have a couple of QoL changes to make, so I'll change the wording for all of this and clean up the file a bit to make it easier to understand.
