### ISSUE TITLE
item max feature

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#144]
Is it possible to add a feat to have a maximum item on the bag.

I mean like

ITEM_MAX_POKE_BALL=50
or
ITEM_MAX_SUPER_POTION=30

The bot will keep max 50 pokeball, and max 30 super potion, and drop the rest if you get more than.

**Comment by RobertMcCoy** [comment]
This might severely clutter up the DropItems and Properties file, but it's something to look at. I might look at doing this later tonight, but I think once we get a new UI overhaul this will be easier to setup visually.

**Comment by EiTeR94** [comment]
Okay thank mate

**Comment by kyleshrader** [comment]
Yeah, once we have config in UI this will be easy to implement.

**Comment by kyleshrader** [comment]
We will worry a lot less about a cluttered config file... maybe move to json? :heart:

**Comment by SwipeX** [comment]
@kyleshrader with config UI json/xml/binary file will be sufficient.

**Comment by SippieCup** [comment]
implemented.

https://github.com/SwipeX/PokeMate/pull/282
