### ISSUE TITLE
more movements

### ISSUE THREAD

**Issue by pikachukaki** [SwipeX/PokeMate#149]
can you add more movements and a config to maximise the area to walk on..also if you can make random movements in this area cause many pokemons aren't in the streets...
Also if you can add a way to loore the char to pokestops with lure! :P Thanks!

**Comment by kyleshrader** [comment]
```
#Range to walk in, VERY sensitive
range=.02
#points in the map path
map-points=20
```

**Comment by pikachukaki** [comment]
so thats what they doing...range in what miles km or something else? a bit of explain in the values?

**Comment by kyleshrader** [comment]
range is for the width/height of the box... i'd say 0.001 comes out to ~1 block
map-points is the number of points it picks around the map to navigate too. I'd suggest 5-20

**Comment by kyleshrader** [comment]
Maybe for your final request, we can prefer to travel by lured pokestops when determining our next paths to move along.. And maybe have an option to farm lured pokestops, as an attempt to appear more realistic.

**Comment by pikachukaki** [comment]
that could be great cause i see much movement without nothing happening!
also an option to release to the doctor low cp pokemons!

**Comment by kyleshrader** [comment]
Honestly, I stopped caring about the eggs and turned up the speed to 10.00

**Comment by ghost** [comment]
If you still want to hatch eggs, set your speed to 4.40

**Comment by kyleshrader** [comment]
Have you tested this? :D Is it spotty or always increments

**Comment by ghost** [comment]
Yeah, I'm still using it to hatch eggs as we speak-- if you want to be on the safe side, you can set it to 4.00 instead

**Comment by pikachukaki** [comment]
4.40 isnt working...stuck at 4.2km

**Comment by ghost** [comment]
Might wanna make it run for a bit. It takes about 800 seconds to hatch a 5km egg.

**Comment by pikachukaki** [comment]
4.00 doesnt see to work either :/

**Comment by ghost** [comment]
It won't immediately hatch eggs. You have to wait.

**Comment by pikachukaki** [comment]
im looking the km's but they stuck

**Comment by BurakDev** [comment]
@pikachukaki You have to wait MORE

**Comment by ghost** [comment]
It's not that fast. It takes nearly half a minute to increment the in-game km counter by .1

**Comment by pikachukaki** [comment]
so the km's arent updating regularly!ok will try again!!

**Comment by ghost** [comment]
To clarify, it takes roughly:
25 seconds to increment by .1 kilometers
500 seconds to hatch a 2km egg
1,250 seconds to hatch a 5km egg
2,500 seconds to hatch a 10km egg

**Comment by pikachukaki** [comment]
to clarify it im talking about this 
Incubated : yes
State : 2,8/5.0km
this is what iam looking and saying it stuck!
Im not expecting an egg to hatch in 10secs :package: 

Also a feature to be able to enable more incubators!

**Comment by ghost** [comment]
Again, it takes 25 seconds for it to increase by .1 km.
Your egg will hatch in about 9 and a half minutes.

**Comment by SwipeX** [comment]
@pikachukaki it does use all able incubators.

**Comment by SippieCup** [comment]
Issue is now offtopic. Closing thread.
