### ISSUE TITLE
Eggs wont hatch

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#15]
eggs don't hatch until you actually login the game, I guess its because they need to be clicked ?

happened 3 times now, as soon as I login as normal the egg auto hatches

**Comment by SwipeX** [comment]
API does not currently support cracking the eggs, only incubating them to the point of cracking. Still waiting for that feature.

**Comment by null-dev** [comment]
Appears to be implemented in the API now, read the comments in this issue: https://github.com/Grover-c13/PokeGOAPI-Java/issues/188

**Comment by vmarchaud** [comment]
Maintainer of PokeGOAPI-Java here, they are hetched by the pogo server automatically, the request is just used to get a notification to the app.

**Comment by null-dev** [comment]
@vmarchaud But when I use the bot, it doesn't start incubating a new egg until I open the app to crack the old one...

**Comment by mjmjelde** [comment]
@vmarchaud @null-dev is right.  You must receive the notification of the hatching before the inventory is updated to show the new pokemon and that the incubator is no longer in use

**Comment by SwipeX** [comment]
Will add this in :) thanks.
