### ISSUE TITLE
Api key error

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#150]
I dunno if it's caused by the new release,

but i get this :s 

![capture](https://cloud.githubusercontent.com/assets/20646280/17194481/82dcde64-5458-11e6-81b6-32c5619e248d.PNG)

My API is working for a pokemon go map scanner, but not for the bot

**Comment by kyleshrader** [comment]
I got this last night... it seems to happen after you just create your api key. I had to wait a few minutes

**Comment by kyleshrader** [comment]
Did you just create your key, or have you had it for a while?

**Comment by EiTeR94** [comment]
got it for a while, and i regenerate it, still got the same error

**Comment by ghost** [comment]
Please make sure that the Google Maps Directions API is enabled: https://console.developers.google.com/apis/api/directions_backend

**Comment by kyleshrader** [comment]
try deleting your token.txt and reverifying the token.

**Comment by EiTeR94** [comment]
@Silverdesu it's activated 
@kyleshrader i delete it, and create a new API key, delete token folder, still have the issue 

I will wait few min maybe

**Comment by EiTeR94** [comment]
![capture](https://cloud.githubusercontent.com/assets/20646280/17194866/b917beca-545a-11e6-8ca2-50066cfdaf06.PNG)

got this now, mush better? ^^

**Comment by SippieCup** [comment]
Its likely you reached the maximum free number of requests allowed for your API key within a 24 hour period. use another google account and make a second key.

**Comment by ghost** [comment]
Create a new project, activate Directions API, take key from that.
You don't need a second account.

**Comment by SippieCup** [comment]
Ah, I thought it was account-wide. My mistake!

**Comment by EiTeR94** [comment]
Ok guys, thx you all, issue solved
