### ISSUE TITLE
[Not an issue] How to hatch eggs + How to not get softbanned

### ISSUE THREAD

**Issue by ghost** [SwipeX/PokeMate#151]
Quoting myself from #149 here:

To hatch eggs, set your speed (in properties) to anything equal to OR below 4.470.
At 4 meters per second, it will take roughly:
25 seconds to increment by .1 kilometers
500 seconds to hatch a 2km egg
1,250 seconds to hatch a 5km egg
2,500 seconds to hatch a 10km egg

A simple trick to not get softbanned: Don't be stupid.
Don't randomly teleport to different nations in a short amount of time.
Keep your speed lower than 70 miles per hour (keep the value under 31.29)
Don't teleport to South Korea.

If you want to still travel around the world to get more captures, follow this simple guide:
1) Google for "timer." Google will bring up a timer.
2) Go to Google Maps.
3) Get directions from your bot's current location to the location you want to be.
4) Check for the SHORTEST path possible, whether it be via plane or trams.
5) Plug that time into the timer.
6) SHUT DOWN THE BOT.
7) Start the timer.
8) When the timer ends, teleport to the new location.

This is going on the SAFE side, if you're really paranoid about getting banned.
Usually I've seen that you can stop the timer when there's about an hour remaining and still not get banned.

**Comment by TGDredge** [comment]
I have seen that you can set your speed to 17.5 and still incubate eggs.

**Comment by SippieCup** [comment]
That is correct, because Pokemon Go calculates distance walked once a minute. If your new location is < 300 meters in a straight line than the previous location, it will add the difference to the eggs. 

This means that unless you are walking directly in a straight line, moving faster will still incubate eggs, however it might be slightly slower. If your speed is under 5.00, the distance will always count.

**Comment by Sorries** [comment]
Does a VPN help for location spoofing ?

**Comment by RobertMcCoy** [comment]
You can "spoof" your location by entering in any long/lat or address on earth. From my experience the server saves your last logged in location, and if you move to another location in an unreasable amount of time (across the country in 15 minutes) you will be softbanned.

**Comment by rherartt** [comment]
I am not sure why but when I increase my speed to 4.00 it takes waaaay longer to hatch

**Comment by kylestev** [comment]
Since this is in the Wiki, I'm going to close this issue. Thank you for the contribution @Silverdesu -- I'll add it to the readme as well 😄
