### ISSUE TITLE
drop_item_list is ignored

### ISSUE THREAD

**Issue by FreakySt0rm** [SwipeX/PokeMate#152]
Hi, my config.properties states:

drop_item_list=ITEM_POTION

But every item except the balls are still being dropped. (Needless to say, after changing the config, I restarted the .jar)

Tagged pokestop [+50xp] - Poke Ball (x1) - Revive (x1) - Razz Berry (x1)
Removed 1 ITEM_RAZZ_BERRY
Removed 1 ITEM_REVIVE

**Comment by RobertMcCoy** [comment]
Can you post the full config.properties?

**Comment by FreakySt0rm** [comment]
# PTC/Google login credentials
username=**************@gmail.com
password=**************
# Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use
use-location-name=false
location-by-name="Trafalgar Square, London"
#Lat/Long
latitude=53.759481
longitude=-2.699925
#Preferred throw item
preferred_ball=ITEM_POKE_BALL
#Google maps API key for walking
api-key=*******************************************
#What IV% to keep pokemon at
iv-ratio=90
#What CP to keep pokemon above
min-cp=1500
#show user interface
show=true
# should the bot EVER drop items (true/false)
drop_items=true
# Meters per second
speed=4.40
# Automatic evolving 
automatic-evolving=true
#Range to walk in, VERY sensitive
range=.02
#points in the map path
map-points=30
# Only whitelist certain pokemons
whitelisted-pokemon=
# List of Pokémons ids to NEVER transfer, separated by commas.
never-transfer=
# Enable events notifications on console output
console_notification=true
# Enable toast notifications on UI (only if UI is enabled)
ui_notification=false
#Enable popup notifications
sys_notification=true
# Enable auto eggs incubating
eggs_incubating=true
# Enable auto eggs hatching
eggs_hatching=true
#Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)
drop_item_list=ITEM_POTION

**Comment by jdmloki** [comment]
I have the same problem, my drop list only included potion and razzberry, bot dropped everything including my max potions.

**Comment by FreakySt0rm** [comment]
`# PTC/Google login credentials
username=
password=

# Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use

use-location-name=false
location-by-name="Trafalgar Square, London"
#Lat/Long
latitude=53.759481
longitude=-2.699925
#Preferred throw item
preferred_ball=ITEM_POKE_BALL
#Google maps API key for walking
api-key=
#What IV% to keep pokemon at
iv-ratio=90
#What CP to keep pokemon above
min-cp=1500
#show user interface
show=true

# should the bot EVER drop items (true/false)

drop_items=true

# Meters per second

speed=4.40

# Automatic evolving

automatic-evolving=true
#Range to walk in, VERY sensitive
range=.02
#points in the map path
map-points=30

# Only whitelist certain pokemons

whitelisted-pokemon=

# List of Pokémons ids to NEVER transfer, separated by commas.

never-transfer=

# Enable events notifications on console output

console_notification=true

# Enable toast notifications on UI (only if UI is enabled)

ui_notification=false
#Enable popup notifications
sys_notification=true

# Enable auto eggs incubating

eggs_incubating=true

# Enable auto eggs hatching

eggs_hatching=true
#Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)
drop_item_list=ITEM_POTION`

**Comment by FreakySt0rm** [comment]
Sorry, the insert auto-formatted the text lol

**Comment by FreakySt0rm** [comment]
I notice some comments have a space after the # and some do not. This would not affect the parsing of the values would it?

**Comment by ssbtoday** [comment]
> I notice some comments have a space after the # and some do not. This would not affect the parsing of the values would it?

The # indicates a comment, so it doesn't matter whether there is a space or not afterwards.

**Comment by RobertMcCoy** [comment]
that shouldn't affect the outcome. Currently there is another version of the dropping system that should be more cleaner. I'm going to hold off on making any changes until that PR gets pushed, then if this persists afterwards I'll look into it. 

Though, are either of you running via command prompt? I'm not able to replicate this bug, but I can provide you with a line of code to put in that would help me identify this bug.

**Comment by FreakySt0rm** [comment]
I thought as much, but thought I'd check lol

**Comment by FreakySt0rm** [comment]
I'm running via command prompt: java -jar pokemate.jar

**Comment by RobertMcCoy** [comment]
I need someone compiling it from source each time that's encountering this bug to attempt to identify the problem. Anyone that's experiencing this and running the program in console with "gradlew run"?

**Comment by ashgh** [comment]
## I am running it via gradlew run and it is not working for me. I have the ui disabled and notifications disabled except for console output

seephor

**Comment by FreakySt0rm** [comment]
I've just cloned and run via gradlew run and the fault is no longer present

**Comment by FreakySt0rm** [comment]
[00:27:03] - Tagged pokestop [+50xp] - Poke Ball (x2) - Super Potion (x1)
[00:27:22] - Tagged pokestop [+50xp] - Poke Ball (x1) - Potion (x1) - Razz Berry (x1)
[00:27:36] - Caught a Gloom (644 CP) (Candy: 10)
[00:27:44] - Caught a Pidgey (197 CP) (Candy: 10)
[00:27:51] - Caught a Pidgey (97 CP) (Candy: 13)
[00:27:51] - Pidgey has evolved into Pidgeotto costing 12 candies
[00:28:00] - Hatched CUBONE with 572 CP  - candy: 10  exp: 500  stardust: 800
[00:28:07] - Caught a Jigglypuff (539 CP) (Candy: 38)
[00:28:08] - Now incubating egg ( 2.0km)

> Building 75% > :run

**Comment by RobertMcCoy** [comment]
I don't think my portion of the program made it into the lastest jar release, so I think that's why you guys are having issues with this :)

**Comment by ssbtoday** [comment]
This is why I wish the changelogs for the releases actually noted what actually changed between them.
