### ISSUE TITLE
(NOT AN ISSUE) Just an Idea - Pokestops

### ISSUE THREAD

**Issue by jdmloki** [SwipeX/PokeMate#153]
Would be awesome if there was away to set the bot to walk only, and just grab pokestops and hatch eggs, so when you are low on PokeBalls you can just farm back up.

**Comment by BurakDev** [comment]
Already on my to-do list :+1:

**Comment by jdmloki** [comment]
Awesome! I'd offer my help but java isn't my strong spot!
