### ISSUE TITLE
Hatched eggs show incorrect name

### ISSUE THREAD

**Issue by ashgh** [SwipeX/PokeMate#156]
[19:58:15] - Hatched egg -5433426716476581400 candy: 6  exp: 200  stardust: 461

**Comment by SwipeX** [comment]
This occurs when the hatched pokemon is not added to the Pokebank in time. You will still get the pokemon. Not 100% sure if anything can be done for this. Open to suggestions

**Comment by ashgh** [comment]
going to try updating the inventory again before looking up pokemon in bank

**Comment by ashgh** [comment]
updating inventory seems to work... hatched two eggs and the names show up. only downside is extra update to inventory.

**Comment by SippieCup** [comment]
I agree with SwipeX that there is not much else that can be done for this issue now. There is a lock before any API call so any error like this that you see is going to be from niantic's end.

Closing thread, If this persists or someone has a solution, feel free to reopen or create a new thread.
