### ISSUE TITLE
Crash after 2 hours.

### ISSUE THREAD

**Issue by paradoxism13** [SwipeX/PokeMate#16]
The automation crashed about 2 hours in and spammed these.

http://imgur.com/a/B0Tiw

**Comment by SwipeX** [comment]
I've tried to fix these, but it will require more testing.

**Comment by SwipeX** [comment]
I think google login causes the most issues, but still will require more thought.

**Comment by kyleshrader** [comment]
It looks like we wait for pokegoapi to implement the refresh_token code. i've been messing w/ it on my bot, using their development branch... Looks liek there is still some issues on their side though.

**Comment by BurakDev** [comment]
Since the token refresh is implemented, need try to reproduce this issue

**Comment by agusmba** [comment]
over 3h running here.

Had a disconnection at the 2h mark, but it reconnected immediately (refreshed the token). It seems to be fixed!

**Comment by BurakDev** [comment]
Same for me, reconnected immediately. :+1:

**Comment by agusmba** [comment]
4h mark, several exceptions, and automatic reconnection :+1:
