### ISSUE TITLE
[ERR] Google auth error

### ISSUE THREAD

**Issue by ericksuryadinata** [SwipeX/PokeMate#161]
given this error
![y](https://cloud.githubusercontent.com/assets/20630687/17202720/21fe8382-54c5-11e6-8f60-88383a2456fb.png)

**Comment by Hawkey3s** [comment]
run your cmd as an admin

**Comment by ericksuryadinata** [comment]
@pisuthutton still get the same .. i don't know, but i'm running another bot(different source) and get this too ..

**Comment by Controless** [comment]
This is happening to me too, wasn't happening with the previous version.

**Comment by mark3717** [comment]
I have the same issue on osx, even when trying with sudo.
I'm running version 0.2.1, previous version 0.1.9 worked for me...

**Comment by SippieCup** [comment]
This is a problem with the API. Its being worked on, please stand by!

**Comment by SkanderHelali** [comment]
Global. https://github.com/jabbink/PokemonGoBot/issues/545

**Comment by SippieCup** [comment]
After smashing my head into the keyboard for an hour, it seems that Niantic may have actually just broke new google logins entirely. 

Unless you have previously logged in and have valid tokens from before, you will not be able to login on any device or bot.

**Comment by Hawkey3s** [comment]
@SippieCup How's your keyboard?

**Comment by gerardcuadras-zz** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/293

**Comment by Mewks** [comment]
Yep thats good news. Just gotta wait for a new release build (jar).

**Comment by kyleshrader** [comment]
think we will need to update anything on our end?

**Comment by SippieCup** [comment]
We do, I have it done. Just waiting on the servers to come back up before I commit it to my branch and do a pull request.

**Comment by EiTeR94** [comment]
Servers are coming up slowly

**Comment by SippieCup** [comment]
Fixed in my repo, can grab the latest release if you dont want to wait for SwipeX to release his:

https://github.com/SippieCup/PokeMate

Pull request to SwipeX made.

**Comment by EiTeR94** [comment]
@SippieCup Thx mate !

**Comment by EiTeR94** [comment]
servers are up, and still go the same issue 

![capture](https://cloud.githubusercontent.com/assets/20646280/17208661/e90c1400-54b9-11e6-82fe-851444618150.PNG)
![capture1](https://cloud.githubusercontent.com/assets/20646280/17208664/ead181d0-54b9-11e6-9012-6e0045e1b6b5.PNG)

**Comment by SippieCup** [comment]
The Current SwipeX repo will not login.

Until he pulls my changes if you want to use the bot you will have to use it from my repo that I linked above.

**Comment by EiTeR94** [comment]
I used your release 2.1.1 from your repo and get this error

**Comment by SippieCup** [comment]
EiTeR94, My mistake. I uploaded the wrong binary. Try again.

**Comment by EiTeR94** [comment]
Perfect mate thx !

**Comment by EiTeR94** [comment]
Well, sorry but i get a new error 

![capture](https://cloud.githubusercontent.com/assets/20646280/17209472/7a91856a-54bd-11e6-8c18-1ebb19a8da81.PNG)

My API key have not reached the maximum request per day, it's a new key with 0 request.
And google api map is activated.

**Comment by SippieCup** [comment]
please ensure that you have enabled the google maps directions API as well.

**Comment by EiTeR94** [comment]
yes 
![capture](https://cloud.githubusercontent.com/assets/20646280/17209601/28cf77cc-54be-11e6-8d98-73b4f578505c.PNG)

It's on a new google account, so the limit request is ok
I will wait few min maybe it's just from google issue.

**Comment by SippieCup** [comment]
Oh. use the new config.properties.template file. my code has renamed the configuration names so that it is only underscores in names.

Ex:

`api-key` is now `api_key`

**Comment by ericksuryadinata** [comment]
:+1: Thx for this, but I'll wait until SwipeX pull your request, maybe he sleep right now :D

**Comment by SippieCup** [comment]
Sure, whatever floats your boat.

Looking at the config you posted, that is the issue. The only other thing I would say is you should reduce your map-points to 20 or so. 150 points will max out the API in 3 runs.

To get it working now. In config make the following changes

api-key -> api_key
iv-ratio -> iv_ratio
min-cp -> min_cp
automatic-evolving -> automatic_evolving
map-points -> map_points
whitelisted-pokemon -> whitelisted_pokemon
never-transfer -> never_transfer

**Comment by EiTeR94** [comment]
Ok, it's fixed with your new config.properties file.

I put 150 cause 20 is too little and the path doesnt take the entire range :/

**Comment by ericksuryadinata** [comment]
@SippieCup I clone your git, it give me something 
C:\Users\TOSHIBA\Downloads\Run for BOT MAP>cd C:\Users\TOSHIBA\Documents\GitHub\Test\PokeMate

C:\Users\TOSHIBA\Documents\GitHub\Test\PokeMate>java -jar pokemate-all-0.2.1.1.jar
Using default config.properties location
Logged in as ******
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:86)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:74)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:85)
        at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
        at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)

C:\Users\TOSHIBA\Documents\GitHub\Test\PokeMate>pause
Press any key to continue . . .

**Comment by SippieCup** [comment]
server is down, try again in a second.

**Comment by ericksuryadinata** [comment]
okay, I'll closed after PR's done

**Comment by Dragon92** [comment]
@SippieCup I get a StackOverflow exception when I run the bot:

C:\Users\Dragon\Desktop\PokeMate-2.1.1>java -jar pokemate-all-0.2.1.1.jar
Using default config.properties location
Exception in thread "main" java.lang.StackOverflowError
        at java.util.regex.Pattern$Branch.match(Unknown Source)
        at java.util.regex.Pattern$GroupHead.match(Unknown Source)
        at java.util.regex.Pattern$LazyLoop.match(Unknown Source)
        at java.util.regex.Pattern$GroupTail.match(Unknown Source)
        at java.util.regex.Pattern$BranchConn.match(Unknown Source)
        at java.util.regex.Pattern$CharProperty.match(Unknown Source)
        at java.util.regex.Pattern$Branch.match(Unknown Source)
        at java.util.regex.Pattern$GroupHead.match(Unknown Source)
        at java.util.regex.Pattern$LazyLoop.match(Unknown Source)
        at java.util.regex.Pattern$GroupTail.match(Unknown Source)
        at java.util.regex.Pattern$BranchConn.match(Unknown Source)
        at java.util.regex.Pattern$CharProperty.match(Unknown Source)
        at java.util.regex.Pattern$Branch.match(Unknown Source)

... and so on.

**Comment by SippieCup** [comment]
Did you set up a config.properties file?

**Comment by Dragon92** [comment]
Yup, used the new one with the underscores.

**Comment by SippieCup** [comment]
What version of java are you using?

**Comment by Dragon92** [comment]
Java Version 8 Update 101 (build 1.8.0_101-b13)
I've had no runtime issues with it before that login error.
