### ISSUE TITLE
Images won't show up in UI?

### ISSUE THREAD

**Issue by Brandon00151** [SwipeX/PokeMate#163]
So I downloaded the bot and it runs great but the UI looks a little bare. Compared to the image in the Readme my UI looks nothing like it. The bot runs fine but the UI.  I get images in my notifications but not my Pokemon list,Item list etc. http://i.imgur.com/mRKLCKz.png

**Comment by ghost** [comment]
Update to the latest version of Java and see if your issue is resolved.

**Comment by Brandon00151** [comment]
it worked! Thanks!
