### ISSUE TITLE
1.5 Release error

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#17]
https://i.imgur.com/TxZRLZ8.png

**Comment by paradoxism13** [comment]
Just got this too using the .jar

**Comment by Gaffney90** [comment]
Clone the latest code that was updated one hour ago.

**Comment by Simpuhl** [comment]
How do you compile it tho?

**Comment by SwipeX** [comment]
I dont have time to figure out the token expiration atm, ill update this when I can.

**Comment by Simpuhl** [comment]
Your latest temp fix version is working again, can login
