### ISSUE TITLE
What happens when no pokeballs are left?

### ISSUE THREAD

**Issue by teyhouse** [SwipeX/PokeMate#171]
I am using Hyperballs right now, will the bot use the other pokeballs if i no longer have Hyperballs?

**Comment by SippieCup** [comment]
yes it'll go down in quality if you run out of the selected one.

**Comment by ghost** [comment]
iirc once you run out of balls the bot will continue to wander until it gets balls (from pokestops)

**Comment by arkdelkaos** [comment]
This is a question that almost everyone on my clan is asking me xD 
I think that you may want to add it to the `readme.md`, or to the `config.properties.template` comments :)

**Comment by SippieCup** [comment]
Resolved, closing thread.
