### ISSUE TITLE
Cant login with Google

### ISSUE THREAD

**Issue by Raphael-Os** [SwipeX/PokeMate#172]
Hi, I tried to connect with the 0.2.1 release (and 0.2.0) with my google account, and it didnt worked. I used the same credentials with the 0.1.9 release which worked perfectly.

When I use java -jar Pokemate.jar, my console show this:
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

---

 Please go to the following URL
 URL: null
 Code: null (copied to clipboard)

---

Failed to automatically open browser.

there were no exceptions.

**Comment by EiTeR94** [comment]
Wait until SwipeX release the new .jar
or use this version :
https://github.com/SippieCup/PokeMate/releases/tag/2.1.1

**Comment by SwipeX** [comment]
This will be updated shortly.
