### ISSUE TITLE
Build failed, Could not find tools.jar

### ISSUE THREAD

**Issue by JamFox** [SwipeX/PokeMate#173]
Build keeps failing because it can't fin tools.jar even though its here C:\Program Files\Java\jdk1.8.0_45\lib

**Comment by SwipeX** [comment]
your java is still set in your env variables to java 7 it seems?

run `java -version`

**Comment by kylestev** [comment]
What version of Gradle do you have? what is the value of Java home in your
environment variables?

**Comment by JamFox** [comment]
Java version 1.8.0_101, I did a google search before making this issuetopic and changed the value in env variables but it still does not work

**Comment by kylestev** [comment]
If you change the environment variable, you will need to close and reopen the application you were using to run the build task.

**Comment by JamFox** [comment]
I did, still gives me the same error

**Comment by JamFox** [comment]
It's looking for tools.jar from the wrong place Program Files(x86)\Java\jre...

**Comment by kylestev** [comment]
[This StackOverflow answer might help you](http://stackoverflow.com/a/17842012/758310). I am closing this as this isn't a problem with PokeMate, rather your Java development environment.
