### ISSUE TITLE
Pokemate.jar error

### ISSUE THREAD

**Issue by Jarkheld** [SwipeX/PokeMate#174]
When trying to connect i get a lot of errors like the following one:
 at java.util.regex.Pattern$BranchConn.match(Unknown Source)

I'm using SippieCup release which can be found at the following address: https://github.com/SippieCup/PokeMate/releases/tag/2.1.1

How do i fix it?

Thank you so much :)

**Comment by kylestev** [comment]
Open up an issue on their issue tracker.
