### ISSUE TITLE
Incorrect Item Display?

### ISSUE THREAD

**Issue by Micfly** [SwipeX/PokeMate#176]
Currently the bot is level 18 and the UI has been showing the inventory as having 2 incense and 1 extra incubator. It seems to have the correct numbers for pokeballs, revives, and potions but I'm stuck seeing the incense and incubator. Shouldn't there be more incense, lucky eggs, and lures? 
![untitled](https://cloud.githubusercontent.com/assets/20202274/17216302/ff180152-5494-11e6-971e-f84e01e9b5b7.png)

**Comment by iDreamInBinary** [comment]
Correct me if I'm mistaken, but I think the bot doesn't collect levelup rewards, you will get the extra stuff when you log in on your phone
