### ISSUE TITLE
Build Failed - non-zero exit value [Help]

### ISSUE THREAD

**Issue by alansete** [SwipeX/PokeMate#177]
When I try to use gradlew it throws this on cmd:

> `C:\Users\USER\Desktop\PokeMate-2.1.1\PokeMate-2.1.1>gradlew run
> :compileJava
> :processResources
> :classes
> :run
> Using default config.properties location
> com.pokegoapi.exceptions.LoginFailedException: svarzee.gps.gpsoauth.Gpsoauth$TokenRequestFailedLogged in as carlu654y@gmail.coming 75% > :run
> 
> ```
>     at com.pokegoapi.auth.GoogleAutoCredentialProvider.login(GoogleAutoCredentialProvider.java:53)
>     at com.pokegoapi.auth.GoogleAutoCredentialProvider.<init>(GoogleAutoCredentialProvider.java:41)
>     at dekk.pw.pokemate.Context.Login(Context.java:73)
>     at dekk.pw.pokemate.Context.Login(Context.java:39)
>     at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:59)
>     at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
> ```
> 
> Caused by: svarzee.gps.gpsoauth.Gpsoauth$TokenRequestFailed
>         at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:105)
>         at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:88)
>         at com.pokegoapi.auth.GoogleAutoCredentialProvider.login(GoogleAutoCredentialProvider.java:46)
>         ... 5 more
> Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Credential Provider is null
>         at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:75)
>         at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
>         at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
> :run FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':run'.
>   
>   > Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-zero exit value 1
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

I've set up the new files and config, tried doing gradlew fatjar, nothing seems to work. Any ideas? Thanks.`

**Comment by alansete** [comment]
I use those files to login with another account and it actually works, it just has problems with gmail accounts I guess.

**Comment by kylestev** [comment]
Can you try deleting the token file for your gmail and try authenticating
again? the refresh token may have been revoked.

**Comment by alansete** [comment]
How do I delete that token?

**Comment by FabioEight** [comment]
Same issue here. Exactly the same errors.

**Comment by alansete** [comment]
I just made a clean clone and it worked. You can close now, thanks for the assist.
