### ISSUE TITLE
Item's being dropped not in drop list.

### ISSUE THREAD

**Issue by fniroui** [SwipeX/PokeMate#179]
In my case my drop list is:
"drop_item_list=ITEM_POTION,ITEM_SUPER_POTION,ITEM_REVIVE"
Whenever a Super Potion or Revive is dropped all my razz berries are also dropped, and is not recorded in log.

**Comment by SwipeX** [comment]
Your razzberries are being used to catch pokemon, the API does this unless specified otherwise

**Comment by SwipeX** [comment]
since it is a 1.5 catch rate multiplier.
