### ISSUE TITLE
smaller walking area

### ISSUE THREAD

**Issue by munchbox** [SwipeX/PokeMate#18]
Is there a way to make the field in which the bot travels to a smaller area?

Say, to cover a smaller area with a few choice pokestops?

**Comment by munchbox** [comment]
edited title

**Comment by ghost** [comment]
Would love to see this as well.

Maybe an addition to this would be:
- Custom path/coords for the bot to follow/go to when near (set multiple coords and it'll traverse to each when in range) as pokestops don't usually cover all poke spawns.

**Comment by ghost** [comment]
Unable to edit previous post so I'll leave another.

Another suggestion:
- Transverse the map based on PokeVision? Goes to each pokemon location visible on PokeVision. Read coords, walk to the area, repeat. Would depend on PokeVision being up always though. Could have a "if offline wait 30 seconds and attempt to connect again".

**Comment by SwipeX** [comment]
Could possibly add a customization in that allows for you to resize the area and routes. Will have to see how difficult that will be first.

**Comment by null-dev** [comment]
Why do we even need pokevision, don't we have access to the API? Couldn't we just fetch the pokemon locations ourselves (and wouldn't this include pokemon only visible to the current user also)?

**Comment by SwipeX** [comment]
added b7c664ff42aab4285dfe03afb5cddceb92230d3d

**Comment by SwipeX** [comment]
@ range prop
