### ISSUE TITLE
Evolving

### ISSUE THREAD

**Issue by Changleman** [SwipeX/PokeMate#19]
Is there a way to turn off evolving?

Thanks

**Comment by MDashK** [comment]
I would like to turn that off two... Was saving some pokemon and Not evolving them, and as soon as I open the app, they evolved... =S

**Comment by Simpuhl** [comment]
Not yet there isn,t

A feature id like to see is if we don't have the 3rd version of the evolve then don't evolve the first version until there's enough candies to evolve the 2nd version into the 3rd

Also would be nice if you can choose to keep a shit load of pidgy candy so you can pop a lucky egg then evolve them all

**Comment by kyleshrader** [comment]
If you are running it with gradle, just comment out the code in the evolving task. :/

**Comment by Simpuhl** [comment]
Care to share how to use it with gradle? where to download etc?

**Comment by SwipeX** [comment]
We could add a setting i guess. simple pull request if anyone wants to add

**Comment by kyleshrader** [comment]
Looks like it's in the latest release, @Simpuhl but i think it's as simple as getting gradle for w/e operating system, checking out this repository, then typing `gradle run` but you may face complications that are beyond worth it. It's now in the settings of the latest version as of PR #10

**Comment by SwipeX** [comment]
There will be a value for it in the next release.

**Comment by SwipeX** [comment]
b7c664ff42aab4285dfe03afb5cddceb92230d3d
