### ISSUE TITLE
windows 7 x64 install error

### ISSUE THREAD

**Issue by SomeSchmuck84** [SwipeX/PokeMate#192]
!!!! IGNORE !!! I posted in the wrong place.
I used a run.bat instead of using cmd and got the following result:

C:\Users\Bob\Downloads\poke-cruncher-windows\poke-cruncher>pip install -r requir
ements.txt
Collecting click==6.6 (from -r requirements.txt (line 1))
  Using cached click-6.6.tar.gz
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Flask-Cors==2.1.2 (from -r requirements.txt (line 3))
  Using cached Flask-Cors-2.1.2.tar.gz
Collecting future==0.15.2 (from -r requirements.txt (line 4))
  Using cached future-0.15.2.tar.gz
Collecting geopy==1.11.0 (from -r requirements.txt (line 5))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 6))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 7))
  Using cached itsdangerous-0.24.tar.gz
Collecting Jinja2==2.8 (from -r requirements.txt (line 8))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 9))
  Using cached MarkupSafe-0.23.tar.gz
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@1f25e907f3e5f1b60
3330e71041e1ad7bee7580f#egg=pgoapi (from -r requirements.txt (line 10))
  Cloning https://github.com/tejado/pgoapi.git (to 1f25e907f3e5f1b603330e71041e1
ad7bee7580f) to c:\users\bob\downloads\poke-cruncher-windows\poke-cruncher\src\p
goapi
  Error [WinError 2] The system cannot find the file specified while executing c
ommand git clone -q https://github.com/tejado/pgoapi.git C:\Users\Bob\Downloads\
poke-cruncher-windows\poke-cruncher\src\pgoapi
Cannot find command 'git'
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Users\Bob\Downloads\poke-cruncher-windows\poke-cruncher>pause
Press any key to continue . . .

This was on my second attempt to install.
(I should warn: I'm no power user.)

**Comment by exsystemctl** [comment]
You dont really need git to use this, just clone and download the repo.

If you do however just want to type the same command and for it to work, download this: https://git-scm.com/download/win
