### ISSUE TITLE
How to do Step#5 of readme?

### ISSUE THREAD

**Issue by Maroosh1** [SwipeX/PokeMate#199]
Ok, I know ur gonna say that if i don't know that I shouldn't do that or even be here. But please. May be there is a kind person who can explain what to do as if I were the stupidest person on Earth (which I am not actually). So I did 4 steps, dowloaded and installed JDK, opened my Terminal (I'm on Mac) what do I do next? How to "compile and run"? Sounds pretty easy...

**Comment by erasels** [comment]
You download the Pokemate.jar corresponding to the version you're using and put it into the same folder as the config.properties file. You can find all jars and zips here https://github.com/SwipeX/PokeMate/releases

**Comment by pisuth** [comment]
Install gradle https://gradle.org/gradle-download/

navigate to your PokeMate directory and run "gradle clean fatJar" 

The complete jar file should be in your .../build/libs

**Comment by SippieCup** [comment]
@Maroosh1 Were you able to compile it?

If not, there are also binaries available on the [Releases](https://github.com/SwipeX/PokeMate/releases) page.
