### ISSUE TITLE
READ THIS

### ISSUE THREAD

**Issue by SwipeX** [SwipeX/PokeMate#206]
Niantic updated some code, and are throttling requests. Currently some features do not work. While I am waiting for the API to update their files (patiently), functionality will be lacking. Wait patiently and this will be fixed before long.

**Comment by SippieCup** [comment]
This may have actually been fixed now. I think there may be an edge case or two that will cause rate limit failures, but I think we are in a good spot now.

**Comment by SippieCup** [comment]
Niantic added a few more sneaky ways of throttling, the new caching system implemented has solved these issues as well as the API becoming more mature.

Requests only exceed the rate limit when catching pokemon at this time.
