### ISSUE TITLE
Include limits for individual items

### ISSUE THREAD

**Issue by bppdddqqqq** [SwipeX/PokeMate#208]
I want to keep certain items in an amount lower or equal the set amount in the config. Current implementation only allows us to either fully dump them or keep them all.

**Comment by SippieCup** [comment]
Agreed, I will be adding this soon. I have been meaning to add it for awhile.

My thoughts on implementation is a simple `min_item_amount` in the configuration and removing all but that amount.

Won't be hard to implement, I'll have it in soon.

**Comment by gsisso** [comment]
I already made part of it just trying to improve the code as it look awful atm.
my idea is to keep using the same config and just adding the operator = and then the amount you want to keep. for instance if you want to keep 5 item potions you'll do - drop_item_list=ITEM_POTION=5

**Comment by EiTeR94** [comment]
i think it's better to add like this if possible 

MAX_ITEM_POKE_BALL=10
MAX_ITEM_POTION=0
MAX_ITEM_REVIVE=20
etc etc.

**Comment by SippieCup** [comment]
Implemented a quick fix for now in the multithreading pull request 

with min_item_amount. I'll refactor it to specific items at a later time this week.
