### ISSUE TITLE
[Request] Set more map points to "force" route

### ISSUE THREAD

**Issue by arkdelkaos** [SwipeX/PokeMate#217]
![Map Route Screenshot](http://i.imgur.com/GUiPbWV.png)

As you can see at my screenshot, somehow gmaps hates "Calle Nicaragua" and "Paseo del Estanque".
And they are the best zones to catch and tag pokestops :?
I don't know why, sometimes, with the same coordinates, those streets are used...and sometimes they are not. (I tried changing `map_points` value, but I cannot force it without going with a  crazy high value) 
In fact, some of the "streets" that are on use, aren't even _real streets_, but park tracks...how those streets, the main ones, doesn't get preferred over the dirt track ones, is beyond me :?

I know this is a gmaps issue, but **maybe we could force it by configuring some extra POI?**
Like start at X, but you must go from A to B, from C to D, and from E to F, somehow, sometime

**Comment by SippieCup** [comment]
Unfortunately this is not possible. with Google Direction API.

I would suggest using PokeStop Navigation instead for your issue as it is likely to be faster at getting you to your ideal locations in your case.

**Comment by arkdelkaos** [comment]
Nah, I prefer the bot as it is, even if I cannot get to the "good zone".
Is weird that those streets, precisely, are the ones it doesn't use...those are the main ones, and they have a lot of spawn points and pokestops. In fact, somehow it kind of dislike the square around the lake, even when it's the most important of all the park. Is like if the bot dislike to use central park's 97th and 85th, IYKWIM xD

**Comment by SippieCup** [comment]
Can't do anything about this issue, closing thread.
