### ISSUE TITLE
New commit seems to be borked

### ISSUE THREAD

**Issue by FreakySt0rm** [SwipeX/PokeMate#230]
I've just built and run the latest commit and now I'm getting: 

[CatchPokemon] Starting Loop
[Tag PokeStop] 457 Pokestops Found.. Tagging
[Tag PokeStop] Tagging PokeStop in range
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[19:40:22] - Tagged pokestop [+0xp]
[Tag Pokestop] Starting Loop
[CatchPokemon] Hit Rate Limited
[CatchPokemon] Ending Loop
[CatchPokemon] Starting Loop
[Tag PokeStop] Hit Rate Limited
[Tag Pokestop] Starting Loop
[HatchEgg] Hit rate limit
[Update] Error - Hit Rate limiter.
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[Tag PokeStop] Hit Rate Limited
[Tag Pokestop] Starting Loop
[CatchPokemon] Hit Rate Limited
[CatchPokemon] Ending Loop
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[HatchEgg] Hit rate limit
[Update] Error - Hit Rate limiter.
[Tag PokeStop] 457 Pokestops Found.. Tagging
[Tag PokeStop] Tagging PokeStop in range
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[19:40:28] - Tagged pokestop [+0xp]
[Tag Pokestop] Starting Loop
[HatchEgg] Hit rate limit
[CatchPokemon] Hit Rate Limited
[CatchPokemon] Ending Loop
[CatchPokemon] Starting Loop
[Tag PokeStop] Hit Rate Limited
[Tag Pokestop] Starting Loop
[Update] Error - Hit Rate limiter.
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop
[Tag Pokestop] Ending Loop - No Stops Found
[Tag Pokestop] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[CatchPokemon] Starting Loop

I'm using exactly the same lat/long as I was 10 minutes ago, so there shouldn't be a softban issue?

**Comment by SippieCup** [comment]
> [19:40:28] - Tagged pokestop [+0xp]

You seem to be softbanned. Wait a bit and try again.

**Comment by SippieCup** [comment]
> [19:40:28] - Tagged pokestop [+0xp]

It looks like you are softbanned. Try again in a bit.

**Comment by FreakySt0rm** [comment]
I did wonder, I'll let you know.... :)

**Comment by FreakySt0rm** [comment]
I'm actually wondering if there's an issue with the PMT servers. Just logged into the app on my phone and got the server sync icon in the top left constantly going round and when I click on "Nearby", nothing appears. It doesn't do that if I'm softbanned.

**Comment by FreakySt0rm** [comment]
![13903296_10210352563119247_975446744216317548_n](https://cloud.githubusercontent.com/assets/7168758/17272516/e957de62-568f-11e6-88b3-c2fc25866065.jpg)

Yeah, definitely a server related issue - Been like this for 5 minutes with 2 app restarts and even a phone restart

**Comment by gsisso** [comment]
yeah it was a server issue,seem to be working for now
