### ISSUE TITLE
Still not catching Pokemon

### ISSUE THREAD

**Issue by SSinischo** [SwipeX/PokeMate#233]
Sorry to be a pest with more issues, but I am set smack dab in the middle of San Francisco and the bot will not find any Pokemon.  Also it spins a pokestop every once in a while, but is passing by many others and the console still says "No Stops Found"

What's up with this, boys?

**Comment by alc4tras** [comment]
Same with me. Tagged the first pokestop and ignore the rest..

**Comment by beldar** [comment]
Same here, not catching any pokemons!

**Comment by SippieCup** [comment]
Fixed in latest release.

**Comment by beldar** [comment]
I pull the latest from Master and it only walks now... not even pokestops...

**Comment by SippieCup** [comment]
you sure its the latest?

**Comment by beldar** [comment]
Well I did a `git pull origin master` just now.

I'm only getting logs from requests to google maps and it only walks...

**Comment by SippieCup** [comment]
you are probably are sharded to different location. 

if you teleport too quickly niantic will say there are no pokestops or pokemon near you.

**Comment by beldar** [comment]
Shouldn't I see the Threads trying anyway? I'm literally only seeing requests to Google Maps.

BTW I'm sure its not a location problem because I just tried with this one https://github.com/jabbink/PokemonGoBot an works perfectly catching pokemons.

I like yours better for the UI tho!

**Comment by SippieCup** [comment]
I removed a lot of the debug messages. make sure you have notifications enabled in the config if you want them to be output now.

**Comment by beldar** [comment]
My configs looks like: 

``` java
# Enable events notifications on console output
console_notification=true
# Enable toast notifications on UI (only if UI is enabled)
ui_notification=true
#Enable popup notifications
sys_notification=false
```

**Comment by SippieCup** [comment]
Can you try running the latest release JAR and see if that works or if you get the same errors?

**Comment by masterof123** [comment]
```
[CatchPokemon] Ending Loop No Pokemon or No Pokeballs
[16:29:51] - XP Update: 0XP/H
[CatchPokemon] Starting Loop
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException:
 TypeError: undefined is not a function (evaluating '$.notify')
        at com.sun.webkit.dom.JSObject.fwkMakeException(Unknown Source)
        at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at com.sun.webkit.WebPage.executeScript(Unknown Source)
        at javafx.scene.web.WebEngine.executeScript(Unknown Source)
        at dekk.pw.pokemate.PokeMateUI.lambda$toast$0(PokeMateUI.java:83)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Sourc
e)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown S
ource)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[CatchPokemon] Ending Loop No Pokemon or No Pokeballs
```

Just walking around, not tagging stops. Ran out of balls so it aint catching pokemon. I have the GUI open so I can see him walking around.

Both on version 3.0 and 3.1, no change.

**Comment by masterof123** [comment]
Another bot (this one without GUI) log looks like this:

```
[CatchPokemon] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[Tag PokeStop] Ending Loop - No Stops Found
[16:22:49] - XP Update: 0XP/H
[CatchPokemon] Starting Loop
[CatchPokemon] Ending Loop No Pokemon or No Pokeballs
[16:27:28] - XP Update: 0XP/H
[CatchPokemon] Starting Loop
[CatchPokemon] Ending Loop - No Pokemon Found
[16:29:46] - XP Update: 0XP/H
[CatchPokemon] Starting Loop
[CatchPokemon] Ending Loop No Pokemon or No Pokeballs

```

These are both at the default location (Central Park, NY) so we know that there are lots of stops and pokemon to be found.

**Comment by SippieCup** [comment]
Update to the  newest release.

**Comment by arkdelkaos** [comment]
Still nothing :(

**Comment by SippieCup** [comment]
The newest build should not spam those messages. If you are getting them
you are using the wrong one.

**Comment by SippieCup** [comment]
Try the new release.

**Comment by alc4tras** [comment]
I download latest repo and v0.3.1.3 jar.. Still not catching any pokemon and not tagging any pokestop.. But, when I change Nav Type to POKESTOPS, it tag pokestops and catch pokemon.. I don't know why.. I'll just use this setting for awhile..

**Comment by SippieCup** [comment]
Sounds like you may have been softbanned or sharded to a different location. I'm sure if you swapped it back it'll work now. but good to know you got it resolved!

**Comment by arkdelkaos** [comment]
Sorry man, but no softban :( With pokestops, it works...with streets, it doesn't; just walk around, no error msg, nothing on log tab.

Btw, it doesn't drop items too: `[07:38:52] - Tagged pokestop, but bag is full [+50xp]`

~~...And I'm not sure, but it seems like it only catch the pokemons found at spawn point.~~ _(It does catch...it just slow as hell as the pokestops route is not as "good" as the streets one)_
