### ISSUE TITLE
Items not dropping anymore

### ISSUE THREAD

**Issue by GameGrime** [SwipeX/PokeMate#235]
I have my config.properties set as such
`# Items to drop`

`drop_item_list=ITEM_POTION,ITEM_SUPER_POTION,ITEM_REVIVE,ITEM_POKE_BALL`

`#Minimum amount of each item to save`

`minimum_item_amount=35`

So I don't max out my inventory. Because it seems like the bot will drop all my razzberries if i get maxed out. That's a whole different issue.

Now the bot is not dropping any of those items even though I have over 50 Potions and 100 Pokeballs.

**Comment by alc4tras** [comment]
and didn't tag pokestops.. Only the first pokesop tagged..

**Comment by abhijit4569** [comment]
I'm able to tag pokestops manually. But PokeMate doesn't.

**Comment by SippieCup** [comment]
Fixed in latest release.
