### ISSUE TITLE
multiple windows -- same account?

### ISSUE THREAD

**Issue by masterof123** [SwipeX/PokeMate#236]
I downloaded the latest version, created 5 new gmail accounts, set up the config file 5 times (all the same, except with obviously a different email for each one) and ran them all.

When I open the GUI it looks like every single one is running the same account. Same items, experience, pokemon, etc (even though they aren't all in the same location). 

What's weird is that if I check the command window, they each say "logged into XXX" properly. Any ideas?

I thought it might be that I needed 5 separate Google API keys, but I got a second one and it's the same issue...

**Comment by ghost** [comment]
Are they in separate folders? I was having the same problem till I separated them. I think the tokens get mixed up.

**Comment by alc4tras** [comment]
This happen to me when using same API key for all acounts.. Each account must have their own API key..

**Comment by masterof123** [comment]
I've got a 'bot' account with 5 separate folders inisde it, each of them have their own folder.

4 of htem are using the same API key but the 5th has a separate one. It's still happening.

**Comment by masterof123** [comment]
Oh! I figured it out.

I created all accounts and then when I was logging in, I stayed logged in to the same account. Each time a bot asked for a new verification key or token or whatever, I was logged into the same account. That's why.

I deleted all of my tokens, logged out each time and used a separate key. It's working well now. :)

**Comment by SippieCup** [comment]
You are authorizing the account that the browser is logged into so it is
attaching to the same account.

The way the new authorization works has nothing to do with the account in
the config. All the email actually does is have a '@' in it so it starts
the Google authentication routine.

For each account you need login to the correct email address before
authorizing each account.

Once authorized, the token will take care of the rest.

Let me know if you have any problems.
