### ISSUE TITLE
[Request] Possible to add current level, % exp to level and xp/hr to console ? 

### ISSUE THREAD

**Issue by zippet** [SwipeX/PokeMate#237]
As in earlyer versions, the console had the following information:
- Current level
- Exp to level
- Xp/hr

I would like to request these information back to the console. Since its hard to tell if the bot is actually running + optimzing the config file w/o the gui.

Admins, please tag/move this ticket if needed.
Thank you in advance.

**Comment by SippieCup** [comment]
Added to console in latest release
