### ISSUE TITLE
Ignore list isn't working

### ISSUE THREAD

**Issue by jordaneads** [SwipeX/PokeMate#239]
I've got a long list of pokemon to ignore, for the sake of saving up balls occasionally.  It still picks them up in game.   Any suggestions/fixes?

**Comment by gsisso** [comment]
are you using the latest version ? also do you compile from sources or using the pre-compiled version ?

**Comment by jordaneads** [comment]
I've just been stashing and pulling, so I'm actually not sure?  Still not very familiar with Git.  I just downloaded the newest zip, unzipped, fixed up the config as I want it.  Then I realized, the .jar file I've been using was downloaded outside of the Git folder itself.  Where does that file come from?  That's what I run everything with, usually.

**Comment by jordaneads** [comment]
![screen shot 2016-07-31 at 11 11 09 am](https://cloud.githubusercontent.com/assets/20635160/17277720/83717650-570f-11e6-85bc-b74c04615557.png)

**Comment by masterof123** [comment]
On git if you go to the "Code" tab, there's a "Releases" tab. You can get the latest pre-complied .jar there. If you download the source code, then you've got to compile it into a .jar yourself.

**Comment by gsisso** [comment]
also please post the config file your using just to make sure that you added the pokemons correctly.

**Comment by jordaneads** [comment]
I've got it fixed now, updated the jar was my issue.  I've been thinking I was running it with the uncompiled code this entire time, and that the jar file I had was doing that for me.  I'm an idiot!  It's running so much smoother now too, before it was freezing every few minutes and I'd have to restart to make it move again.  

Thanks for your help!  Problem solved.
