### ISSUE TITLE
Keep bot running while in sleep?

### ISSUE THREAD

**Issue by masterof123** [SwipeX/PokeMate#240]
After a while, most computers tend to go into sleep mode/hibernate/etc. This stops the bot from running.

Are there any power-saving modes that the bot will continue to run on? Basically I'd like to know what power-saving options I can safely use while having the bot constantly going, rather than just disabling them all completely.

**Comment by Simpuhl** [comment]
You simply set your pc to not sleep...

**Comment by kylestev** [comment]
As @Simpuhl mentioned, you would want to disable the setting that says something along the lines of: automatically put my computer to sleep after X. You can use your favorite search engine to find more info on how to do it for your operating system.
