### ISSUE TITLE
[HatchEgg] Hit rate limit [CatchPokemon] Hit Rate Limited, what do they mean?

### ISSUE THREAD

**Issue by Jarkheld** [SwipeX/PokeMate#241]
Could you please explain what 
[HatchEgg] Hit rate limit
[CatchPokemon] Hit Rate Limited mean?
Are they error?

thank you so much :smile:

**Comment by SippieCup** [comment]
It's just a notification that Niantic rejected the request to the server. They are debug messages in the code for us to troubleshoot any problems you may have. 

Unfortunately the hatchery code needs to be fixed before egg hatching will work.
