### ISSUE TITLE
"Progress Monitor" "XP Update: x.xxxXP/H" Pop-up every 3 seconds

### ISSUE THREAD

**Issue by MDashK** [SwipeX/PokeMate#249]
I guess there's no need for this to be showing everytime in the corner of the screen... Literally every 3 seconds. It's good to be in the log, but not always on-screen like that.

**Comment by SippieCup** [comment]
I'll make it not always run soon. Next work for me is going to be making a prettier console output

**Comment by SippieCup** [comment]
Fixed in latest Release.

**Comment by MDashK** [comment]
Awesome. Thanks!
