### ISSUE TITLE
NumberFormatException null

### ISSUE THREAD

**Issue by kyleshrader** [SwipeX/PokeMate#25]
Are you seeing the NFE w/ null value in Context.java:45?

**Comment by null-dev** [comment]
Check your config, did you set your username?

**Comment by SwipeX** [comment]
We should classify this as an enhancement;
Congis should use readProperty(value, default) incase people have incorrect configs.

**Comment by kyleshrader** [comment]
```
# PTC/Google login credentials
username=xxx@gmail.com
password=xxxxxx
latitude=##.#######
longitude=-###.######
api-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
preferred_ball=ITEM_GREAT_BALL
# should the bot EVER drop items (true/false)
drop_items=true
# Meters per second
speed=2.778
iv-ratio=80
```

What's wrong w/ that?

**Comment by kyleshrader** [comment]
It's failing to parse int for iv-ratio... btw I was getting a diff stack earlier, but now it shows its at Config.java:34

**Comment by kyleshrader** [comment]
Meh, I dont know what's up... I can do `System.out.println(properties.getProperty("iv-ratio"));` but get NFE w/ null value for the parseInt line in there.

**Comment by kyleshrader** [comment]
No longer seeing this issue... i imagine it's my fault >_>
