### ISSUE TITLE
Item dropping not working

### ISSUE THREAD

**Issue by ickis098** [SwipeX/PokeMate#250]
my settings:
drop_items=true
drop_item_list=ITEM_POTION,ITEM_REVIVE
minimum_item_amount=5

At the moment I have >20 of each of these. Using v0.3.1.3.

**Comment by gsisso** [comment]
https://github.com/SwipeX/PokeMate/commit/9b0be72fad879f5197e99d506b135fbb0702df99

at the moment it doesn't use the minimum_item_amount config,I guess it will be fixed today.

**Comment by SippieCup** [comment]
Fixed in latest release.
