### ISSUE TITLE
[bug] Bot is not taking pokemon and pokestop

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#252]
Hi

Since the last update of pokemate 0.3.1.3 , the bot catch no pokemon, no pokestop.
It just runs.
I don't know why, and my config use the last with the STREETS path

![capture](https://cloud.githubusercontent.com/assets/20646280/17287790/f2a88c80-57d1-11e6-9af5-89d2d5421cb5.PNG)

**Comment by EiTeR94** [comment]
after 20min i finaly catch only one pokemon, and still no pokestop tag. my xp per hour is 1k...

**Comment by EiTeR94** [comment]
Ok and after 30min the bot crash and i got this 

![capture](https://cloud.githubusercontent.com/assets/20646280/17288784/f855cada-57d6-11e6-8037-01c0f7b1230a.PNG)

Hope it can help you to fix

**Comment by ickis098** [comment]
I have the same exception when running with UI. Without it (show=false), it works fine (also picking stops, catching mons). Do you have correct coordinates, where some stops are available?

**Comment by iDreamInBinary** [comment]
That crash happens because of a memory leak, vm crashes because its out of memory.

**Comment by EiTeR94** [comment]
Coordinate are on a 2 pokestop. I can see my char move on the GUI, but catch nothing.
And without the GUI, it's the same, catch nothing.

**Comment by theRealMcPanic** [comment]
I have the same problem.
Bot is just walking but not tagging and not catching when navigating in STREETS mode. In POKESTOPS mode it catches and tags just fine, although the range and map_point options seem to have no effect at all.
This behaviour started for me with release 0.3.0.

**Comment by Jarkheld** [comment]
I have the same problem, both with 0.2.6 and 0.3.0

**Comment by alc4tras** [comment]
@theRealMcPanic same with me.. With STREETS it's just like the bot ignore anything, but with POKESTOPS it work fine.. I tell this to @SippieCup in the previous thread, but he/she just conclude that i'm softbanned when i'm not..

**Comment by SippieCup** [comment]
@alc4tras: if you think theres a problem, the code is open source. go fix it.

Until then having 15 open issues on the same thing doesn't help. Nor does complaining about the person giving you free stuff. Especially when there are other factors in play.

**Comment by alc4tras** [comment]
@SippieCup I'm not angry to you.. Like I say before, i'll just use Pokestops setting.. Sadly, I don't understand Java..

**Comment by SippieCup** [comment]
Pushing a new commit and pre-release that will fix all pokestop issues. please use pokestop for the time being. Streets will need to be refactored at a later time and is currently broken. Hopefully I can get to it tonight.

**Comment by SippieCup** [comment]
Fixed in latest build.
