### ISSUE TITLE
a option for always evolving some pokemon

### ISSUE THREAD

**Issue by maarten98** [SwipeX/PokeMate#253]
# always evolve (false or true)

always evolve= true

**Comment by EiTeR94** [comment]
already got this option 

# Automatic evolving

automatic_evolving=true

# Only whitelist certain pokemons

whitelisted_pokemon=
Leave blank after the whitelisted_pokemon
Please read the config.properties

**Comment by maarten98** [comment]
sorry i'm not that of an expert but thanks!

**Comment by alc4tras** [comment]
whitelisted_pokemon=
fill it with pokemon pokedex number that you want to auto evolve..

Edit: @maarten98 Please close this thread if it's already solved and always check for closed thread first before opening new thread..
