### ISSUE TITLE
Not Catching any pokemon

### ISSUE THREAD

**Issue by ghost** [SwipeX/PokeMate#260]
The bot is tagging pokestops properly, but are not catching any pokemon. The only time it captures a pokemon is when I initially start the bot. Other than that it will run for an hour without catching anything on _Santa Monica Pier_ :(. 

I have read other issues that are similar to mine and none seem to address the same problem or offer a solution. I have been struggling with this the last day or so. I've been trying the new releases every time they came out but none seem to be fixing my issue. There doesn't seem to be any error messages.

I am using the latest release (0.3.1.5). I have tried reinstalling java, rebooting, updating gradle and none seem to help. I've tried messing with a few settings to see if anything is causing it but to no avail.

[Config File](https://gist.github.com/ksaiyanz/ae678bef7e897d970b014d33254d4440)

I'm on Mac El Capitan.

**Comment by SippieCup** [comment]
I just figured out why, been trying to find out all day.

Pokemon arent showing up because Niantic has been limiting map requests. If you request map info too fast it will return no results.

Currently the bot polls the map for every task, we are going to have to refactor the bot to do less map polling.

This will fix the issues with pokemon catching. I'll try and get it done in the next release.

**Comment by MDashK** [comment]
Yeah, I guess they did that with this newest release(?) of the game, because I also noted that issue of "no pkmn" too.

**Comment by SippieCup** [comment]
Yeah, it changed at that time.

**Comment by ghost** [comment]
> Pokemon arent showing up because Niantic has been limiting map requests. If you request map info too fast it will return no results

@SippieCup That makes sense

> I'll try and get it done in the next release.

@SippieCup You are awesome

**Comment by SippieCup** [comment]
Fixed in newest commit.

**Comment by PawlikEfremov** [comment]
Bot isn't collecting Pokestops and Pokemons, just walking and doing nothing.

**Comment by SippieCup** [comment]
In addition to limiting map requests, if you teleport they will also not show up.

Furthermore:

> Bot isn't collecting Pokestops and Pokemons, just walking and doing nothing.

Tells me nothing. Please at least copy/paste the GUI along with the time you copied it so I can see if one or more threads are not updating.

**Comment by PawlikEfremov** [comment]
OK sorry here are the Screenshots from the GUI

**Comment by SippieCup** [comment]
Edited for privacy on your user name. Those errors occur because you are running the GUI. please run it with show=false and see if it still happens.

**Comment by PawlikEfremov** [comment]
Oh, i think i found the failure. After I deactivated Bitdefender Security(Antivirus) it started working properly. Sorry for the circumstances and for my bad english.

**Comment by SippieCup** [comment]
Good to know! Let me know if there are any other issues.
