### ISSUE TITLE
[BUG] Possible bug with minimum item amount

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#263]
There is a bug i think with this option 
# Minimum amount of each item to save

minimum_item_amount=50
# Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)

drop_item_list=ITEM_POKE_BALL

I put 50 to keep minimum 50 item of ITEM_POKE_BALL

When i reach 50 pokeball, the bot drop X50 and not keep 50 pokemon MINIMUM as the config say.

Or maybe i've misunderstanding something?

**Comment by gsisso** [comment]
Fixed in #261

**Comment by SippieCup** [comment]
Yup, Thanks for pointing this out @EiTeR94, and @gsplash for the PR.

**Comment by EiTeR94** [comment]
Np mate, we use your bot, it's normal to report you all the bug we found.
Thanks for the fix ;)
