### ISSUE TITLE
ASYNC CATCH CALL problem

### ISSUE THREAD

**Issue by yuyaukong** [SwipeX/PokeMate#265]
As I run the program, terminal show that 
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
and can not do other operation to gain exp.
Do you know why async catch call?
Actually, I open 2 terminal using pokemate. Is it the reason this happen?

**Comment by SippieCup** [comment]
`ASYNC CATCH CALL` comes from the API. It means that there were too many requests and some were dropped.

We will be fixing this shortly, however besides console spam, this does not negatively effect the bot.

**Comment by Jeffrey-van-Ham** [comment]
Seems like after a certain amount of time the bot crashes and the console is filled with 
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
ASYNC CATCH CALL
