### ISSUE TITLE
Use best pokeball when pokemon is not registered in your pokedex

### ISSUE THREAD

**Issue by ersinpw** [SwipeX/PokeMate#266]
Well, I lost several rare pokemons such as a snorlax or an alakazam :(
<img width="112" alt="screen shot 2016-08-02 at 10 54 49" src="https://cloud.githubusercontent.com/assets/8781415/17322867/0081e1a2-58a0-11e6-8c30-394e5986ac81.png">

Is it possible to look at the pokedex and according to that select the best pokeball?

**Comment by gsisso** [comment]
haven't seen such implement in the pokemon go api so you'ill probably need to ask it there first. what can be done for now is decide which ball to use based on the [pokemon class](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/pokemon/PokemonClass.java)

**Comment by Jarkheld** [comment]
@gsplash how do i set it?

**Comment by gsisso** [comment]
its not possible at the moment but I can implement it if there's demand for it.

though about two ways of implementing : 
1. for each ball provide a list of pokemons you want to catch with this ball.
2.for each ball provide the class you want to catch with it. 

which you like more ? also if you think you got a better idea for this you can always suggest it.
just as I said ,currently we cant know if the pokemon is in your pokedex or not.

**Comment by Jarkheld** [comment]
I'd prefer the 2nd one, in my opinion it would be the easiest to avoid wasting high level balls on not-so-rare pokemons.

**Comment by gsisso** [comment]
Fixed in #288 ,after someone will merge this pr ill try adding another config for using the best ball based on pokemon class.

**Comment by SippieCup** [comment]
@gsplash, I had to manually commit the merge because it would have caused a lot of issues with git. that being said, it has been committed.
