### ISSUE TITLE
[Suggestion]Catchlisted_pokemon

### ISSUE THREAD

**Issue by yuyaukong** [SwipeX/PokeMate#268]
Some suggestion, is it possible to create a 
catchlisted_pokemon=DRAGONNITE,SNORLAX
that will in decending order of pokemon you want to catch
Since now only catch the first pokemon in the catchable list, is it possible to create a list and catch the preferred pokemon than using default?

**Comment by yuyaukong** [comment]
It will catch dragonnite > snorlax > other if there have multiple pokemon

**Comment by SippieCup** [comment]
The bot now catches all pokemon rather than the one that is first returned as of https://github.com/SwipeX/PokeMate/commit/9a73be9d16e55293fe35d381f983b9519c7a77df

So this is unnecessary.
