### ISSUE TITLE
[BUG] possible bug with drop_item_list

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#269]
Well, my config is
# should the bot EVER drop items (true/false)

drop_items=true
# Items to drop (remove from this list if you want to keep it, note that inventory management will now be left up to you, as it could be possible to run out of pokeballs)

drop_item_list=ITEM_REVIVE,ITEM_POKE_BALL
# Minimum amount of each item to save

minimum_item_amount=40

And the bot drop only ITEM_REVIVE on the consol
I also try with a : 
drop_item_list=ITEM_REVIVE, ITEM_POKE_BALL
A SPACE between , and ITEM_POKE_BALL go the same problem.

**Comment by SippieCup** [comment]
I am aware that ITEM_POKE_BALL doesn't drop, it is not that hard to go into the app and just drop the balls manually.

I will fix this when I get around to it.

**Comment by SippieCup** [comment]
Fixed in newest release
