### ISSUE TITLE
Selects Pokeballs even if you don't have any

### ISSUE THREAD

**Issue by mjmjelde** [SwipeX/PokeMate#27]
My bot is set to use the preferred pokeball as the regular pokeball, but I have run out of them.  So it just tries to keep catching pokemon with a pokeball and always fails.

**Comment by SwipeX** [comment]
Thanks :)

**Comment by SwipeX** [comment]
added in b7c664ff42aab4285dfe03afb5cddceb92230d3d

**Comment by SwipeX** [comment]
to clarify

`Caught a SPEAROW using a ITEM_GREAT_BALL
Transferring 1/2 SPEAROW CP 103 [12/8/10]
Profile update : 291781 XP on LVL 21 42.37 % to LVL 22
Caught a BELLSPROUT using a ITEM_POKE_BALL`
