### ISSUE TITLE
Error close Java UI

### ISSUE THREAD

**Issue by gtuxyco** [SwipeX/PokeMate#273]
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x6aa54423, pid=2844, tid=0x000007f0
# 
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) Client VM (25.101-b13 mixed mode windows-x86 )
# Problematic frame:
# C  [jfxwebkit.dll+0xa84423]
# 
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
# 
# An error report file with more information is saved as:
# C:\Users\pablo\Desktop\Bots\Pokemate\hs_err_pid2844.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

[hs_err_pid2844.TXT](https://github.com/SwipeX/PokeMate/files/397116/hs_err_pid2844.TXT)

**Comment by EiTeR94** [comment]
Try with this 
show=false

It'll desactivate de GUI until a fix

**Comment by SippieCup** [comment]
The fix is moving off of JavaFX or buying more ram.

Otherwise, use show=false.
