### ISSUE TITLE
ASYNC CATCH ALL

### ISSUE THREAD

**Issue by jordaneads** [SwipeX/PokeMate#276]
With the latest release, still having issues with this.  Any solutions?

**Comment by Jarkheld** [comment]
same here :(

**Comment by ashgh** [comment]
These messages are printed from the API. Try restarting the bot without a GUI, if you have it active.

**Comment by Jarkheld** [comment]
it worked :D thanks a lot! UI's "log" tab seems broken aswell

**Comment by jordaneads** [comment]
Still stops after a short while, and at the bottom of the terminal window it prompts for ASYNC CATCH ALL over and over, while not doing anything else.

**Comment by SippieCup** [comment]
This is an issue with the API, not the bot. They are working on fixing it.

**Comment by SippieCup** [comment]
Fixed in newest release.

**Comment by jordaneads** [comment]
Running smooth now!  Great work, Sippie!
