### ISSUE TITLE
Memory Increasing over time

### ISSUE THREAD

**Issue by MDashK** [SwipeX/PokeMate#280]
Just a heads up. There must be something wrong related to memory (RAM) on the program, because over time, it gets bigger and bigger.
I started the program with around 400MB being used, and after around 30min. of usage, it's already getting around 1GB of usage.

Over time, it gets to a point that the program crashes due do the memory, with a warning from JAVA itself popping up on-screen due to the issue. This pop-up only happened to me once, because I still haven't run the program enough time to pop-up again.

**Comment by kylestev** [comment]
duplicate of #100

**Comment by SippieCup** [comment]
Run without the ui

**Comment by MDashK** [comment]
Sorry. Didn't knew. Thanks!
