### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by gffde3** [SwipeX/PokeMate#286]
Hey, if possible I'd like to help out but the slack invite link is invalid so I can't join in the discussion. Would I be able to get a slack invite?

Thanks in advance.

**Comment by gerardcuadras-zz** [comment]
Seems to be working perfect. [Link](https://frozen-sea-68189.herokuapp.com/)

**Comment by gffde3** [comment]
Yeah. I get to the email login field but after hitting join I get:

Failed! invite_limit_reached

I think it's a 100 user pending invite limit on slack that has to be resolved by those guys.

edit: they had the same issue here after a quick google https://github.com/tejado/pgoapi/issues/94

**Comment by maxi2mc** [comment]
I would be interested in this also.

**Comment by SippieCup** [comment]
Working on this.

**Comment by SwipeX** [comment]
I'm just waiting for them to respond.

**Comment by SwipeX** [comment]
FIXED
