### ISSUE TITLE
no more consol log

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#290]
Since the last update, there is no more log in the consol is it normal?
Oh, and drop item list seems to not work too.

**Comment by SippieCup** [comment]
I added two new configuration items into the config.properties file.

first is

`console_ui=true` to enable the console UI.

second is the new item management list: https://github.com/SwipeX/PokeMate/pull/282

`drop_item_list=ITEM_POTION,ITEM_SUPER_POTION,ITEM_MAX_POTION:100,ITEM_HYPER_POTION:50,ITEM_RAZZ_BERRY:20,ITEM_REVIVE:40,ITEM_MAX_REVIVE,ITEM_POKE_BALL:30`

**Comment by EiTeR94** [comment]
console_ui fix the console log thx

is this correct : 

#To customize each items min amount add a colon after the item and the min amount to keep, leaving it blank will default it to 0, ie ITEM_POTION is the same as ITEM_POTION:0
drop_item_list=ITEM_POTION,ITEM_POKE_BALL:20,ITEM_GREAT_BALL:50,ITEM_HYPER_BALL:50,ITEM_SUPER_POTION:30,ITEM_MAX_POTION:25,ITEM_HYPER_POTION:25,ITEM_REVIVE:30,ITEM_RAZZ_BERRY:20
cause if it's correct, the bot doesnt drop anything

**Comment by SippieCup** [comment]
set `minimum_item_amount=0`

**Comment by EiTeR94** [comment]
yeah it's already set like that, but nothing is dropped :/

**Comment by SippieCup** [comment]
do you have this in your config? `drop_items=true`

**Comment by EiTeR94** [comment]
yeah

**Comment by SippieCup** [comment]
What version are you using?

**Comment by EiTeR94** [comment]
the last one who's released 1hour ago 0.3.3.1

**Comment by SippieCup** [comment]
can you copy your config file here, minus the username, password, and location parameters?

**Comment by EiTeR94** [comment]
```
#What IV% to keep pokemon at
iv_ratio=80
#What CP to keep pokemon above
min_cp=450
#show user interface
console_ui=true
show=false
# should the bot EVER drop items (true/false)
drop_items=true
# Meters per second
speed=4.40
# Automatic evolving
automatic_evolving=true
#Range to walk in, VERY sensitive
range=.004
#points in the map path
map_points=50
# Only whitelist certain pokemons
whitelisted_pokemon=PIDGEY,PIDGEOTTO,RATTATA,ZUBAT
# List of Pokémons ids to NEVER transfer, separated by commas.
never_transfer=
# Enable events notifications on console output
console_notification=true
# Enable toast notifications on UI (only if UI is enabled)
ui_notification=false
# minimum item
minimum_item_amount=0
#Enable popup notifications
sys_notification=false
# Enable auto eggs incubating
eggs_incubating=true
# Enable auto eggs hatching
eggs_hatching=true
# To customize each items min amount add a colon after the item and the min amount to keep, leaving it blank will default it to 0, ie ITEM_POTION is the same as ITEM_POTION:0
drop_item_list=ITEM_POTION:0,ITEM_POKE_BALL:20,ITEM_GREAT_BALL:50,ITEM_HYPER_BALL:50,ITEM_SUPER_POTION:30,ITEM_MAX_POTION:25,ITEM_HYPER_POTION:25,ITEM_REVIVE:30,ITEM_RAZZ_BERRY:20
# Minimum CP for a pokemon to have a pop-up message (All pokemon that are caught will still be logged)
minimum_cp_for_ui_message=0
# Prefer IV over CP when transfering? true keeps highest IV, false keeps highest CP
transfer_prefers_iv=false
#navigation type can be either STREETS or POKESTOPS
navigation_type=POKESTOPS
```

**Comment by SippieCup** [comment]
are you sure you have items to drop? it probably already cleared out your inventory. it looks right.

**Comment by EiTeR94** [comment]
on the console log it says bag is full and no item 
![capture](https://cloud.githubusercontent.com/assets/20646280/17366701/d4522c8e-598c-11e6-966f-df3d11d40ed8.PNG)

**Comment by SippieCup** [comment]
it is probably full of items you do not have on the list such as ultra and great balls.

**Comment by SippieCup** [comment]
ITEM_HYPER_BALL:50 should be ITEM_ULTRA_BALL:50

**Comment by EiTeR94** [comment]
oh okay will try

EDITE : okay mate it's fixed thanks you for you help and take time for me !

**Comment by EiTeR94** [comment]
edited thx!
