### ISSUE TITLE
bot barely working

### ISSUE THREAD

**Issue by masterof123** [SwipeX/PokeMate#291]
It's unclear how well my bots are running, but it's clear they're not running very well. They all seem to walk around but they don't seem to tag stops. They catch pokemon, but they seem to do it very rarely. 

I'm running the latest version (new GUI looks great btw) and my bot has walked around central park for 6 minutes so far without catching a single pokemon or tagging a simple stop. And it's walked by at least three stops so far.

It's been like this for a few days now. My bots seem to be gaining exp, but at a very slow rate. Probably gained one level total across the last 2-3 days...

**Comment by SippieCup** [comment]
Yes, that because the API was (and still is) broken due to Niantic's changes.

Thankfully, the release 3 minutes ago should resolve almost all of these issues.

The past few days have been bad because Niantic have been actively working against us and the Java API had to do major re-writes. 

Please try the latest release, 0.3.3.1 and see if it resolves your issues.

**Comment by nastye** [comment]
0.3.3.1 doesn't perform any better for me.

**Comment by SippieCup** [comment]
> 0.3.3.1 doesn't perform any better for me.

Can you give a little more information than that?

0.3.3.1 doesn't work any better for me could be because you are still running at 80,000XP/H

**Comment by EiTeR94** [comment]
are you using
navigation_type=STREETS
you have to change to POKESTOPS cause the street option is broken for now

**Comment by ickis098** [comment]
It does tag pokestops, however it does not transfer any mons, even though it should (based on paramerers)

**Comment by ickis098** [comment]
Oh, i've replaced my original config with the new one (basically just removed options, which are no longer supported), and now it does transfer the mons. So I suggest you do the same & check if it works any better.

**Comment by nastye** [comment]
@SippieCup of course, sorry. I let it run at the default position in Central Park. Catches a mon every.. 10 minutes maybe, tagging a stop here and there. Max 1500 XP/hr.

@EiTeR94 's suggestion of changing navigation_type to POKESTOPS seems to help, went to 50k XP/hr at least.

**Comment by EiTeR94** [comment]
as i said to you, STREETS mode is broken, 
https://github.com/SwipeX/PokeMate/releases/tag/0.3.2

**Comment by masterof123** [comment]
Changing the navigation mode to streets has brought significant improvements. They're tagging stops and catching shit.

Where are you getting 80k XP/H? I seem to be getting 30~60k at central park, which I assumed was the best location. My speed is also 3.00. Is there a faster speed that's still safe?

Also, the Log tab doesn't work in the new GUI. It doesn't log anything. I guess that's a separate issue though... The others all seem to be working fine!

**Comment by EiTeR94** [comment]
to see log on console type on the config.properties
console_ui=true

you can up your speed to 4,40, if i don't say bulshit that's the max speed you can put for hatching eggs

**Comment by nastye** [comment]
5.0 still hatches eggs.

**Comment by SippieCup** [comment]
5.0 has an extremely unlikely  case of not counting, using 4.97 will always make it count.

Fixes all issues in this, Log tab should work again now. Please make a new issue with a more accurate title to the actual issue if one still exists.
