### ISSUE TITLE
Range is uninfluential when navigation_type=POKESTOPS

### ISSUE THREAD

**Issue by ianket** [SwipeX/PokeMate#297]
When you have navigation_type set to the POKESTOPS mode, changing the rang won't matter anymore (Eg. see image)

![b60021f5b1bcc7e8d9c680ab8f403bdd](https://cloud.githubusercontent.com/assets/12576303/17376405/bc20ddf8-59b5-11e6-9f67-6978076ba75f.png)

**Comment by Jarkheld** [comment]
try to increase map_points

**Comment by ianket** [comment]
@Jarkheld Tried it, nothing changes (probably since map_points are related to STREETS naviagtion type)

**Comment by SippieCup** [comment]
This is done intentionally. Mapping every pokestop in a range that big will make your bot never actually run

https://en.wikipedia.org/wiki/Travelling_salesman_problem

It only goes to pokestops within that range, but starts out with a smaller set and then slowly grows it by 1 stop each time Navigate is called.

**Comment by ianket** [comment]
@SippieCup Understood
