### ISSUE TITLE
Import EggPokemon not found

### ISSUE THREAD

**Issue by pashorizer** [SwipeX/PokeMate#3]
I can't find this import

`import com.pokegoapi.api.pokemon.EggPokemon;`

Do I have to checkout the PokeAPI to get this working or is the snapshot dependency enough?

**Comment by SwipeX** [comment]
The snapshot, which is bundled with gradle, is enough. you can check C:/user/.gradle and see if it is there and possibly delete it and try to re-download?

**Comment by pashorizer** [comment]
I deleted it from .gradle and re-downloaded it. But for some reason it does not get the latest jar.

**Comment by pashorizer** [comment]
Okay got it working by telling gradle to force download via

```
configurations.all {
    // Check for updates every build
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

  compile ('com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT'){changing = true}
```

**Comment by SwipeX** [comment]
I've had a few issues with gradle/jitpack as well. glad you figured it out.
