### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mjmjelde** [SwipeX/PokeMate#30]
Fix your shit yo!

This is spammed in the console after about an hour or two of use.  No idea where it is coming from.

http://pastebin.com/3ZGQD8K3

**Comment by SwipeX** [comment]
Yeah, it definitely has to do with the map. Just not sure exactly what causes it.

**Comment by SwipeX** [comment]
http://stackoverflow.com/questions/23467797/javafx-nullpointerexception-when-rendering-big-image

**Comment by SwipeX** [comment]
Likely to do with the Polygon[] for the drawn path.

**Comment by SippieCup** [comment]
> Fix your shit yo!

Buy more RAM brah.

Real-talk though theres not much that can be done until we move away from JavaFX. Closing thread. Once we implement a new GUI We'll see if this issue still occurs.
