### ISSUE TITLE
Bot does not walk

### ISSUE THREAD

**Issue by luizkowalski** [SwipeX/PokeMate#304]
My bot does not walk anymore.
this is the current output

```
→ java -jar build/libs/pokemate-all-0.3.3.2.jar
05 Aug 2016 11:19:58 [main] INFO  PokeMate:97 - Using default config.properties location
05 Aug 2016 11:19:59 [main] INFO  PokeMate:69 - Using Coordinates 52.535997688954716, 13.430137849290443
D/GoogleUserCredentialProvider: 3600
D/GoogleUserCredentialProvider: Refreshed Token xxxxxxxxx
05 Aug 2016 11:20:00 [main] INFO  PokeMate:74 - Logged in as aaaaa@gmail.com
```

and thats the only output. I can leave it open for hours, nothing will happen.
If i enable the UI, I see that the bot only blinks, never moves.

**Comment by EiTeR94** [comment]
hide your mail dude

And the API is broken ATM, there is some dev on it, working hard to break the new U6 you can get update here https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by luizkowalski** [comment]
Ah, I see...
Thanks :D
