### ISSUE TITLE
Not Moving

### ISSUE THREAD

**Issue by Imcompletegamer** [SwipeX/PokeMate#307]
I have my google map API key and all in my configs, but my character is just standing still forever.

Heres the top of my config.properties file:
`# PTC/Google login credentials
username=HeyGoodSir78@gmail.com
password=HIDING
# Location by name: e.g. "Sydney" or "W12 8LP" or "Trafalgar Square, London" - set to true to use

use_location_name=false
location_by_name="Trafalgar Square, London"
# Lat/Long

latitude=40.774578
longitude=-73.972774
# Preferred throw item

preferred_ball=ITEM_POKE_BALL
# Google maps API key for walking

api_key=HIDING`

An image of the Pokemate UI if you want it:
[http://prntscr.com/c31pnq](http://prntscr.com/c31pnq)

**Comment by EiTeR94** [comment]
https://github.com/SwipeX/PokeMate/issues/300

**Comment by SippieCup** [comment]
We have not pushed the API update for the safety of our less technical users. once the API gets to a place where we feel comfortable about safety we will update the repo.

**Comment by SippieCup** [comment]
The new release is now safe enough for our standards, please update to the newest release and use the new config.properties template.
