### ISSUE TITLE
Getting Google Map issues with 0.1.7

### ISSUE THREAD

**Issue by boblhead** [SwipeX/PokeMate#31]
I have my API Key in just fine, and 0 issues with previous version, anyone else experience this?

Jul 24, 2016 9:08:36 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #1
Jul 24, 2016 9:08:36 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #2
GoogleMapView.mapResized: triggering resize event
Jul 24, 2016 9:08:37 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #3
Jul 24, 2016 9:08:38 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #4
Jul 24, 2016 9:08:40 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #5
Jul 24, 2016 9:08:43 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #6
Jul 24, 2016 9:08:45 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #7
Jul 24, 2016 9:08:50 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #8

**Comment by mjmjelde** [comment]
Have you hit your daily limit for queries?  This is what usually happens when you hit the limit

**Comment by boblhead** [comment]
Ill request a  new key and report back.

**Comment by boblhead** [comment]
Solved with new API, you can close thanks.
