### ISSUE TITLE
Copy past the link 

### ISSUE THREAD

**Issue by EiTeR94** [SwipeX/PokeMate#310]
How to copy past the link on the console log?
There is no link opened like the previous version :/

**Comment by ghost** [comment]
https://github.com/SwipeX/PokeMate/pull/311
Added.

**Comment by EiTeR94** [comment]
Perfect mate thx !

**Comment by EiTeR94** [comment]
can it be release on a new version? i can't compile myself

**Comment by SippieCup** [comment]
I'll release 4.1 shortly with this update shortly.
