### ISSUE TITLE
Bot doesn't seem to evolve pokemon

### ISSUE THREAD

**Issue by Controless** [SwipeX/PokeMate#313]
Here is my config: http://pastebin.com/raw/FgciYqjp

Can someone please explain why the bot isn't evolving any pokemon? I'm sure I have hundreds of pidgey candies and yet no evolutions occur. Thanks.

**Comment by massivemark** [comment]
My experience is that you mgiht have misspelled a name of a pokemon. One misspelled name made it not evolve everyone.

**Comment by Controless** [comment]
Good idea, I changed 'NIDORAN' and 'NIDORINA' (my pokemon name typo) to 'NIDORAN_MALE' and 'NIDORAN_FEMALE'. However, my pokemon still don't seem to evolve unfortunately (and I'm sure the others are spelled correctly).

**Comment by massivemark** [comment]
try starting small and add 1 pokemon at the time. that way you can see where the mistake is made.

**Comment by Controless** [comment]
Thank you for the tip, now evolving works properly! The issue has something to do with 'NIDORAN_FEMALE' so I just removed it from the list.
