### ISSUE TITLE
[question] is softban reported / detected by bot?

### ISSUE THREAD

**Issue by ickis098** [SwipeX/PokeMate#314]
After successfully running for ~1,5hr, the bot stopped doing anything. Or better said, it still runs between pokestops, but doesn't tag, catch, etc. Restarting doesn't help & i have a suspicion, i got softban, but how can i confirm that? Or was the Niantic again implementing some new security feature?
Anyone else having the same issue?

**Comment by gsisso** [comment]
what is your walking speed?

**Comment by maxi2mc** [comment]
I noticed a softban also, after running 2 accounts on same machine for 30 minutes. Speed is 1.8 for one, and 2 for the other.

**Comment by ickis098** [comment]
my speed is 4. it was working in previous releases..

**Comment by ickis098** [comment]
Lowered the speed to 2, got softban after 3min. I guess they now have some very easy way to detect the bot..

**Comment by maxi2mc** [comment]
If you think of the operations per second you can do with your phone, and then look at the bot, I would say it's pretty clear.

**Comment by SwipeX** [comment]
@maxi2mc that's a valid point. I assume the 100k+ exp per hours days are gone.

**Comment by maxi2mc** [comment]
I was always asking myself why are they not banning anybody. Now I think they are fine-tuning their algorithms on accounts flagged as bots :).

**Comment by gsisso** [comment]
well Im runnig 1 instance of the bot and its working fine,guess it has something to do with the account history of botting and/or amount of instances running by the same ip & device

**Comment by SippieCup** [comment]
Softbans are not flagged as bots by Niantic that we know of. It is very possible to get soft banned on real devices when you have poor connectivity and driving. I don't think its anything to worry about.

That being said, if you get soft banned it will continue until you stop playing for 30 minutes or use a bypass (which is not available in the standard release of PokeMate.
