### ISSUE TITLE
screen keeps refreshing

### ISSUE THREAD

**Issue by massivemark** [SwipeX/PokeMate#316]
hello,

I have osx and my screen keeps refreshing, it makes scrolling in the menus allmost impossible. is there anything i can do about this? thx

**Comment by SippieCup** [comment]
We are developing a new GUI interface so that will probably not be fixed until we move off of java FX. I usggest running the consoleUI interface. I'll be making a couple facelifts to it in upcoming releases to have it give as much information as the GUI version gives.
