### ISSUE TITLE
[Question] Device configurtion

### ISSUE THREAD

**Issue by veskoz** [SwipeX/PokeMate#317]
Hi, Just a question do we must specify a Device and an os version ? And if so, do we choose it randomly? I own only android devices

**Comment by SwipeX** [comment]
We are going to make this more clear in the future, but yes, currently iOS devices require less information to be sent back to niantic.  We feel this gives users the least chance of being caught. If you choose not to put a setting for a device, we have a set a default value that it will select.

**Comment by veskoz** [comment]
Thank you for the fast answer, and ofc for the hard work you guys are pulling off !

**Comment by SippieCup** [comment]
its safe to use an iOS device alongside an android device, I personally use a work iPhone and Android every day so I doubt it'll raise any flags.

If you want to be more believable, I would identify as an iPad.
