### ISSUE TITLE
I will no longer be committing changes to pokemate. 

### ISSUE THREAD

**Issue by SippieCup** [SwipeX/PokeMate#324]
Although pokemate users have always been extremely nice, I can't say the same about the rest of the pokemon go community. I have recieved (and ignored) a cease and desist until this point but will be stopping development of anything related to Niantic as of today. 

My cease and desist does _not_ include pokemate which is free for anyone to build upon, however I will not be participating in any further development. 

I will probably not be making any more incremental updates to reverse engineering,  pokemon go dev, or pokemate other than maintenance changes. 

For those using my private maps, they will be shut down shortly. 

I'm going back to focusing on 3ds and source engine development and wish the best for all of you. 

Thanks, 

SippieCup

**Comment by kyleshrader** [comment]
:beers: Cheers :)
