### ISSUE TITLE
Tagging pokestops does not increase your XP

### ISSUE THREAD

**Issue by agusmba** [SwipeX/PokeMate#34]
I'm not sure if it's a problem with the API, or if there's some other method that needs calling after `loot()`

All my pokestop tagging is like the one below, they don't increase XP. Just in case, I also checked beforehand that my items' bag was not full:

```
Profile update : 43300 XP on LVL 9 81,11 % to LVL 10
Profile update : 43300 XP on LVL 9 81,11 % to LVL 10
Tagged pokestop [+100xp]
Profile update : 43300 XP on LVL 9 81,11 % to LVL 10
Profile update : 43300 XP on LVL 9 81,11 % to LVL 10
```

**Comment by MDashK** [comment]
I can confirm this issue too.

**Comment by SwipeX** [comment]
It seems like the check for Pokestop#canLoot was removed. I added it back in. We can leave this issue open until it is confirmed fixed.

**Comment by agusmba** [comment]
It works now as of commit  [bd01863]
Thanks!
