### ISSUE TITLE
Fatal error in JAVA Runtime

### ISSUE THREAD

**Issue by MDashK** [SwipeX/PokeMate#35]
With this newest release, I get an error as soon as I try to catch a Pkmn:

A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000642f51eb, pid=5072, tid=0x0000000000001c28
JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [jfxwebkit.dll+0xd651eb]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

I can post the rest of the log, if needed.

**Comment by null-dev** [comment]
I don't think we can fix this (it's C++ code in the JavaFX library).

**Comment by MDashK** [comment]
Well, all I can say is that this issue only happens to me in this latest 0.1.7 version. Not in the previous 0.1.6 version...

**Comment by SonnyX** [comment]
Probably due to 449e347f8b749dc314e49573ba13540fe6e05750 (changed how paths were shown)
or less likely as I believe its already in 1.6: 53e17307333011c60fc4bcd89456340a22cd065b

**Comment by SwipeX** [comment]
Correct that it most likely has to do with the PolyLine[] drawing.

**Comment by MDashK** [comment]
Yeah, when I looked at the changes from both versions, I also suspected it was related to the PolyLine change. So, what can I do to fix this? Any ideas?

**Comment by MDashK** [comment]
As of version 0.1.8, this no longer happens to me. Seems to be fixed. Thanks! =D

**Comment by SwipeX** [comment]
As far as I am aware, (I actually have gotten this a few times), this has not occurred for me in quite a while. I'll close this, but if it happens again, reopen this or at least reference it.
