### ISSUE TITLE
0.1.8 build still no xp gained from pokestops

### ISSUE THREAD

**Issue by Skitals** [SwipeX/PokeMate#39]
Love the UI update, but I'm still not getting any experience from tagging pokestops. I'm using a pretty small area with a lot of pokestops... is it possible it's attempting to tag stops before they refresh?

**Comment by MDashK** [comment]
Yeah... I also noticed this too...

**Comment by techinaflash** [comment]
Having the same issue

![2016-07-25 18_14_47-java -jar pokemate jar](https://cloud.githubusercontent.com/assets/8398061/17119425/c08d791a-5293-11e6-9b8a-5e0cdca2177a.png)

**Comment by Messna** [comment]
I think it does work, it just doesn't update the XP until it catches a Pokemon:

```
Profile update : 394080 XP on LVL 22 59,08 % to LVL 23
Tagged pokestop [+100xp]                               (I have no idea why it says 100 here)
Profile update : 394080 XP on LVL 22 59,08 % to LVL 23
Caught a STARYU using a ITEM_POKE_BALL
Tagged pokestop [+50xp]
Profile update : 394390 XP on LVL 22 59,39 % to LVL 23 (Got 310 XP - 50+50+210)
Caught a PARAS using a ITEM_POKE_BALL
Tagged pokestop [+50xp]
Profile update : 394650 XP on LVL 22 59,65 % to LVL 23
```

Can you check that?

**Comment by SippieCup** [comment]
This was due to the GUI thread and Task thread calling at different times. This has been resolved with the new threading implementation.
