### ISSUE TITLE
Fatal error in JAVA Runtime... Again...

### ISSUE THREAD

**Issue by MDashK** [SwipeX/PokeMate#44]
Changed location, and getting this error for some reason in this new location:

EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000640e51eb, pid=9660, tid=0x00000000000024b8

JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [jfxwebkit.dll+0xd651eb]

Don't know why it's happening now... Nothing changed from other version, except location...

**Comment by MDashK** [comment]
I noticed that in this new location, as soon as it starts, it shows up the Pokestop tagged and gives the error... But the map has not yet loaded the red lines... Maybe it's related?

UPD: OK, no, I just tried it again, and gave me the error in the old location...
I have no idea why this happens, it worked OK for 2 or 3 times, about 1 hour each time, and now it's always giving out this error...

UPD #2: after a few tries, finally worked again... But it's definitelly related to the red lines it creates...

**Comment by SwipeX** [comment]
Could possibly have to do with RAM, I would assume the amount of points for the line polygons is quite large. Ill have a look at doing something about that.

**Comment by MDashK** [comment]
Any news on this issue resolved?
Because with this latest version, I already open the app 20 times, and always get the error before drawing the red lines on the map... =(

UPD: It's useless.. This latest commit does run... It just doesn't... Always returns the FATAL EXCEPTION error... =S

UPD 2: OK, I think I managed to solve it by updating the config file to use the newest "range" and "map-points" variables. Since I didn't had those values in the file, the program was creating a sh*t ton of "ways" to go to... Better make sure to always give away the config file with the newest JAR file. =)

**Comment by SippieCup** [comment]
Resolved.
