### ISSUE TITLE
how the fuck do you open this shit

### ISSUE THREAD

**Issue by sugmagaming** [SwipeX/PokeMate#5]
i got the release and put it in a folder with the properties file set up and nothing happens when i double click the jar

**Comment by Skitals** [comment]
If only they were kind enough to include those instructions on the Releases tab:

java -jar Pokemate.jar

**Comment by SwipeX** [comment]
You will need both java 8, and a command line (DOS or terminal). 
run `java -jar Pokemate.jar` from inside the same folder.
Eventually the UI will allow for double clicking the jar.

**Comment by sugmagaming** [comment]
lol ty
