### ISSUE TITLE
Sidebar doesen't display Pokémons

### ISSUE THREAD

**Issue by purrowler** [SwipeX/PokeMate#50]
The Sidebar does doesent load any Pokémons. 
Everytime it refreshes the UI this error pops up in the console:

> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
>         at com.pokegoapi.api.inventory.CandyJar.getCandies(CandyJar.java:80)
>         at com.pokegoapi.api.pokemon.Pokemon.getCandy(Pokemon.java:150)
>         at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:162)
>         at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
>         at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
>         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
>         at java.lang.Thread.run(Unknown Source)

I tried it with a different account and it loads fine on that one.

**Comment by kyleshrader** [comment]
Fixed by #38

**Comment by dubcanada** [comment]
I'm getting the same error at https://github.com/SwipeX/PokeMate/issues/46 are you sure this is fixed by #38? Cause it seems to be a NPE on getCandies (see my issue for a link to a pull request).

**Comment by kyleshrader** [comment]
Do you have a Hypno on the account that worked, @dfg260 ? How about the account that did not work?

**Comment by capito-tar-gz** [comment]
For practicality sake, can we hide the error or briefly explain this in the app, so it doesn't take up so much real-estate in the terminal?
