### ISSUE TITLE
Better and smarter display of line on console mode

### ISSUE THREAD

**Issue by sachka** [SwipeX/PokeMate#68]
I added a "Caught a CP XXX [xx/xx/xx] Pokemon using a ITEM_POKE_BALL" print to my version.

System.out.println("Caught a " + "CP " + encounterResult.getWildPokemon().getPokemonData().getCp() + " [" + encounterResult.getWildPokemon().getPokemonData().getIndividualAttack() + "/" + encounterResult.getWildPokemon().getPokemonData().getIndividualDefense() + "/" + encounterResult.getWildPokemon().getPokemonData().getIndividualStamina() + "] " + target.getPokemonId() + " using a " + ball.getItemId().name());

It would be nice to get it to print it in color and a more legible line with more info.

Cheers

**Comment by SwipeX** [comment]
`encounterResult.getWildPokemon().getPokemonData()` can be null.

**Comment by sachka** [comment]
it is used only if successful  (after your if)

**Comment by SippieCup** [comment]
Implemented, closing thread.
