### ISSUE TITLE
No GUI on click with Google Login

### ISSUE THREAD

**Issue by thatsmyface** [SwipeX/PokeMate#70]
I'm aware that the reason that you can't start the JAR by clicking on it is because Google Accounts require authentication, and that you can still open the UI by the command line. However, I think I may have a solution. I'm not sure how he did it, but [this](https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API) bot can log in to a Google Account without the authentication. I'm not sure if the method he uses will also work in Java (because he is using Python), but I thought it was worth looking in to. I don't have the knowledge to add this to the project but was hoping you would so that I (and many others) could enjoy the convenience of not having to go in to the command line every time we want to start the bot. 
-Ethan

EDIT: Incase I didn't make it clear the bot is located at: [https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API](https://github.com/TomTheBotter/Pokemon-Go-Bot-Working-Hack-API)

**Comment by BurakDev** [comment]
Create a batch/shell file starting the bot.

**Comment by SwipeX** [comment]
@thatsmyface we are really just waiting on a pull request from the api. They have been working on Google authentication token refreshing, and as soon as they push it, the bot will become a 'double click' app.

**Comment by SwipeX** [comment]
Fixed. https://github.com/SwipeX/PokeMate/commit/e99f7b3063660cfc8c84c5c50e54583f3f2d1da0
