### ISSUE TITLE
Session timed out after 30 minutes?

### ISSUE THREAD

**Issue by Hawkey3s** [SwipeX/PokeMate#73]
It seems like after authenticate using google.com/device we're not storing and make use of refresh token.
Access token only lasts for a short period of  time. When the access token expire, it's trying to get the user to go to google.com/device to authenticate again.

We should cache the user information and store the tokens.

**Comment by SwipeX** [comment]
#70

**Comment by SwipeX** [comment]
Fixed https://github.com/SwipeX/PokeMate/commit/e99f7b3063660cfc8c84c5c50e54583f3f2d1da0
