### ISSUE TITLE
[SUGGESTION] copy 8 character code for google sign-in to the clipboard

### ISSUE THREAD

**Issue by ChiIIerr** [SwipeX/PokeMate#76]

**Comment by SwipeX** [comment]
No need really after commit https://github.com/SwipeX/PokeMate/commit/e99f7b3063660cfc8c84c5c50e54583f3f2d1da0, You only have to do this one time now as long as the token can refresh.

**Comment by ChiIIerr** [comment]
Oh sweet! See, it was so recent I didn't even know that was put in yet. Thanks again for replying to these and keeping up with updates. This has been the best bot to use by far for myself. Really appreciate it!

**Comment by SwipeX** [comment]
Ok, ill close this then, cheers.
