### ISSUE TITLE
Better Evolve

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#79]
Is it possible for us to hold off on evolving until we have have an X amount of evolves ready? 

This way it can pop a lucky egg before it does it?

Also if it has lets say 150 Squirtle Eggs it should save 4 Squirtle minimum. This way it will evolve the best 3 and still keeping 1.

I actually collected a ton of Pidgey's. My goal was to sign in and have this evolve them for me but instead of mass evolving it "TRANSFERRED" everything first, thus only keeping 1 and then evolved only the single 1 I had left and then evolving things after each catch.

It should evolve first and then transfer worst case scenario. That seems like a bug to me

**Comment by SwipeX** [comment]
This definitely ties to #75. We can change the order of evolve and transfer actually that is a good idea.

**Comment by Simpuhl** [comment]
Yes sorry for the duplicate. I guess my suggestion just adds to that one. Would the 2nd part of my comment be considered a bug the fact that it transferred instead of evolved when I had a massive amount of candy and pidgeys?

**Comment by SwipeX** [comment]
Not a bug, just unpreferrable action.

**Comment by Simpuhl** [comment]
Sounds good, maybe if you have time switch up the order. That would be sweet.

by the way thanks for all this. you are an awesome coder. Wish i could get into this. I work in IT but the only programming I ever did was in VB. Any recommended classes I should take to be able to learn what you do? Ill be taking a Java class next semester.

**Comment by SwipeX** [comment]
Order is changed ;p

I strongly recommend data structures, and intro to java's and learning more about the java vm. Then just dive into it.
