### ISSUE TITLE
Unable to launch UI 0.1.2

### ISSUE THREAD

**Issue by Gaffney90** [SwipeX/PokeMate#8]
So I clones the repo 10 minutes ago with the updated src/main folder, edited the config file and ran java -jar Pokemate.jar dekk.pw.pokemate.PokeMateUI

It has launch java -jar Pokemate.jar dekk.pw.pokemate.PokeMateUI 

But it's just showing the command prompt updating with the actions, it appears that the UI hasn't launched. I've attached a screenshot of the folder layout.

![untitled-2](https://cloud.githubusercontent.com/assets/20617800/17080444/b9e9d2ba-5127-11e6-8339-ef609cd05a83.png)

**Comment by ghost** [comment]
I'm getting the same issue.

**Comment by SwipeX** [comment]
This appears to be a bug within the executable configuration.

**Comment by SwipeX** [comment]
I will be able to fix this in a few hours.
