### ISSUE TITLE
Is the display still broken or is it something on my end?

### ISSUE THREAD

**Issue by ghost** [SwipeX/PokeMate#82]
![9ad4f11568](https://cloud.githubusercontent.com/assets/20650661/17150236/42fa90ea-5334-11e6-8479-b84378104edf.png)

**Comment by SonnyX** [comment]
Seems about right...
But no, it seems things are broken on your side, do you perhaps see an error inside of the terminal?
Also which version are you running?

**Comment by ghost** [comment]
Running the 0.1.9 build from half an hour ago-- no errors on my end (other than the occasional Thread-2, which is another thing altogether)

**Comment by TechGuard** [comment]
I have the exact same problem. running the latest .jar file.

**Comment by SwipeX** [comment]
@Silverdesu @TechGuard  what OS may I ask?

**Comment by ghost** [comment]
Windows 10 x64 running on an Intel i5-4210u

**Comment by SwipeX** [comment]
That's exactly what I'm running and the jar gives me no issue.
Edit: is there no errors printing?

**Comment by TechGuard** [comment]
I'm also running Windows 10. No errors btw

**Comment by SwipeX** [comment]
Have either of you run 1.8 without this error

**Comment by ghost** [comment]
Nope, this also happens in 1.8

**Comment by SwipeX** [comment]
That's particularly weird. I would assume javafx is to blame in this case. Are you on the latest java version? 8u101?

**Comment by TechGuard** [comment]
These are my specs:

> java version "1.8.0_65"
> Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
> 
> Windows 10 x64

**Comment by SonnyX** [comment]
I am on Linux (Ubuntu gnome 16.10) and have no problems.

```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by ghost** [comment]
I'll update to 8u101 and tell you the outcome in about 15 minutes

**Comment by SwipeX** [comment]
Okay, well as long as you are on java 8u1 or greater it shouldn't be an issue. Otherwise, I really have no idea on this.

@SonnyX linux ftw.

**Comment by TechGuard** [comment]
Okay, I fixed the issue by updating to Java 1.8.0_101
Thank you very much for the quick response.

**Comment by SonnyX** [comment]
@SwipeX Even when GRUB decides that your boot-sector is missing and tells you to pull commands out of your ... to fix it, it still is lovely.

**Comment by ghost** [comment]
after updating to 8u101 (previously 8u73) I can confirm that the UI is working properly.

maybe throw this onto troubleshooting?

**Comment by SwipeX** [comment]
Will do. Somehow your java installation(s) must have had some issues.
