### ISSUE TITLE
[Suggestion] Toast messages require tweaking

### ISSUE THREAD

**Issue by SonnyX** [SwipeX/PokeMate#89]
There is quite a lot of information in the Toast messages,
Now every time a Pokemon is caught, two to three toast messages are made (caught, evolved, transferred).
This is especially true when just starting up the program, I personally also find the log messages interesting, since the console messages were removed there is nowhere currently to read expired toast messages.

**Comment by SwipeX** [comment]
I would say #90 should suffice for this. Trying to do away with the command line since it makes ease of use increase by a large factor.
