### ISSUE TITLE
Toast messages to UI log

### ISSUE THREAD

**Issue by SwipeX** [SwipeX/PokeMate#90]
The UI should have a navbar link to the log (styled textbox), where the toasts should be logged to after they disappear.

**Comment by RobertMcCoy** [comment]
I've got a working prototype of this, it's set to update the log everytime the player updates (So every 5 seconds). I just need to fix the log spacing, and I will commit the change if it looks good to you. It should look cleaner once I get the spacing issue fixed

![image](https://cloud.githubusercontent.com/assets/2020529/17160552/bc8a104a-5373-11e6-9da6-898bb1f76020.png)

**Comment by BurakDev** [comment]
If you want you can get log from console now, #105

**Comment by BurakDev** [comment]
@RobertMcCoy I think showing this logs need hide the map

**Comment by RobertMcCoy** [comment]
My git just screwed up massively, and I can't make a pull request, but I got the spacing issue fixed, and added more spacing between log entries. I don't think removing the map is feasible for this portion of the program, as this follows the precedent set by the Pokemon and Items tab. I will figure out what's going on with my git and try and create the pull request, for some reason my git thinks it committed to the master of this repository or something.

**Comment by RobertMcCoy** [comment]
@SwipeX Any chance it's saying that I made commit's to this master repo? That's what my local client is saying, and I can't update anything or make pull requests because it says they're out of sync.
