### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by SwipeX** [SwipeX/PokeMate#95]
Any time the user first logs in, or token is not valid, the application should open the default browser to www.google.com/device/ and copy the 8 digit code to the clipboard + display a small pop-up of instructions.

Originally I did not think this important, however, it will allow for first time users to run the jar without using the command line which makes this a much more attractive and easier to use app.

**Comment by SippieCup** [comment]
The new API method implemented last night makes it so you use a static token, this makes it so that you don't need to have this setup anymore.

**Comment by SwipeX** [comment]
still have to authorize once.
